/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rural_housing;

import java.awt.Color;
import java.sql.*;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhik
 */
public class applicant_main extends javax.swing.JFrame {
Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement st = null;
    /**
     * Creates new form applicant_main
     */
    public applicant_main() {
            conn c = new conn();
        con=c.getconn();
    
        initComponents();
    add_detail.setVisible(false);
    view.setVisible(false);
    app_home.setVisible(true);
    g.add(f);
    g.add(m);
    ms.add(ma);
    ms.add(unma);
    ms.add(wi);
    view1.setVisible(false);
    }

    public applicant_main(String abc) {
    initComponents();
    conn c = new conn();
    con=c.getconn();
    app_no.setText(abc);
    app_no1.setText(abc);
    add_detail.setVisible(false);
    view.setVisible(false);
    app_home.setVisible(true);
    g.add(f);
    g.add(m);
    ms.add(ma);
    ms.add(unma);
    ms.add(wi);
    view1.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g = new javax.swing.ButtonGroup();
        ms = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        app_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        app_no = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        add_det = new javax.swing.JButton();
        view_det = new javax.swing.JButton();
        home = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        add_detail = new javax.swing.JTabbedPane();
        personal = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        f_name = new javax.swing.JTextField();
        m_name = new javax.swing.JTextField();
        l_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        a_no = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ma = new javax.swing.JRadioButton();
        unma = new javax.swing.JRadioButton();
        wi = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        nextp = new javax.swing.JButton();
        s = new javax.swing.JComboBox<>();
        t = new javax.swing.JComboBox<>();
        v = new javax.swing.JComboBox<>();
        c_no1 = new javax.swing.JTextField();
        g_wrong = new javax.swing.JLabel();
        d = new javax.swing.JComboBox<>();
        dob = new org.jdesktop.swingx.JXDatePicker();
        income = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        inc_get = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        inc_grp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        poc = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        type1 = new javax.swing.JRadioButton();
        type2 = new javax.swing.JRadioButton();
        type3 = new javax.swing.JRadioButton();
        nexti = new javax.swing.JButton();
        doc = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        acy = new javax.swing.JRadioButton();
        acn = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        mcy = new javax.swing.JRadioButton();
        mcn = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        bcy = new javax.swing.JRadioButton();
        bcn = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        icy = new javax.swing.JRadioButton();
        icn = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        mcy1 = new javax.swing.JRadioButton();
        mcn1 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        mcy2 = new javax.swing.JRadioButton();
        mcn2 = new javax.swing.JRadioButton();
        view = new javax.swing.JPanel();
        view_main = new javax.swing.JButton();
        app_no1 = new javax.swing.JLabel();
        view1 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        f_name2 = new javax.swing.JTextField();
        m_name2 = new javax.swing.JTextField();
        l_name2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        gen1 = new javax.swing.JTextField();
        ms2 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        inc1 = new javax.swing.JTextField();
        view_sub = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        app_no2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rural_housing/Logo.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(330, 330, 330))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 180));

        app_home.setBackground(new java.awt.Color(0, 153, 153));
        app_home.setMaximumSize(new java.awt.Dimension(870, 780));
        app_home.setMinimumSize(new java.awt.Dimension(870, 780));
        app_home.setPreferredSize(new java.awt.Dimension(870, 780));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 29)); // NOI18N
        jLabel2.setText("Welcome To Rural Housing Allocation System.");

        app_no.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        app_no.setText("Label");

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel37.setText("Applicant Login");

        javax.swing.GroupLayout app_homeLayout = new javax.swing.GroupLayout(app_home);
        app_home.setLayout(app_homeLayout);
        app_homeLayout.setHorizontalGroup(
            app_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_homeLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_homeLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(app_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_homeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_homeLayout.createSequentialGroup()
                        .addComponent(app_no)
                        .addGap(403, 403, 403))))
        );
        app_homeLayout.setVerticalGroup(
            app_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_homeLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(app_no, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        getContentPane().add(app_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, 780));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        add_det.setBackground(new java.awt.Color(0, 204, 204));
        add_det.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        add_det.setMnemonic('A');
        add_det.setText("Add Applicant Details");
        add_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_detActionPerformed(evt);
            }
        });

        view_det.setBackground(new java.awt.Color(0, 204, 204));
        view_det.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        view_det.setMnemonic('V');
        view_det.setText("View Applicant Details");
        view_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_detActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 204, 204));
        home.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        home.setMnemonic('H');
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        log_out.setBackground(new java.awt.Color(0, 204, 204));
        log_out.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        log_out.setMnemonic('L');
        log_out.setText("Log Out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setText("Applicant Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_det, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(add_det, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(log_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(add_det)
                .addGap(50, 50, 50)
                .addComponent(view_det)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(home)
                .addGap(50, 50, 50)
                .addComponent(log_out)
                .addGap(83, 83, 83))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, 780));

        add_detail.setBackground(new java.awt.Color(0, 153, 51));
        add_detail.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        add_detail.setToolTipText("");
        add_detail.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        add_detail.setMaximumSize(new java.awt.Dimension(870, 780));
        add_detail.setMinimumSize(new java.awt.Dimension(870, 780));
        add_detail.setPreferredSize(new java.awt.Dimension(870, 780));

        personal.setBackground(new java.awt.Color(0, 153, 153));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel11.setText("Add Details");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Name:");

        f_name.setBackground(new java.awt.Color(0, 204, 204));
        f_name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        f_name.setText("First Name");
        f_name.setMinimumSize(new java.awt.Dimension(99, 32));
        f_name.setName(""); // NOI18N
        f_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f_nameMouseClicked(evt);
            }
        });

        m_name.setBackground(new java.awt.Color(0, 204, 204));
        m_name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        m_name.setText("Middle Name");
        m_name.setMinimumSize(new java.awt.Dimension(99, 32));
        m_name.setName(""); // NOI18N
        m_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_nameMouseClicked(evt);
            }
        });

        l_name.setBackground(new java.awt.Color(0, 204, 204));
        l_name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        l_name.setText("Last Name");
        l_name.setMinimumSize(new java.awt.Dimension(99, 32));
        l_name.setName(""); // NOI18N
        l_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_nameMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("Gender:");

        m.setBackground(new java.awt.Color(0, 153, 153));
        g.add(m);
        m.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        m.setText("Male");
        m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMouseClicked(evt);
            }
        });

        f.setBackground(new java.awt.Color(0, 153, 153));
        g.add(f);
        f.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        f.setText("Female");
        f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setText("Contact Number:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setText("Aadhar Number:");

        a_no.setBackground(new java.awt.Color(0, 204, 204));
        a_no.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        a_no.setText("12 Digit Aadhar Number");
        a_no.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_noMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setText("Date Of Birth:");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setText("Age:");

        age.setBackground(new java.awt.Color(0, 204, 204));
        age.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        age.setText("Your Age");
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel9.setText("Marital Status:");

        ma.setBackground(new java.awt.Color(0, 153, 153));
        ma.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ma.setText("Married");

        unma.setBackground(new java.awt.Color(0, 153, 153));
        ms.add(unma);
        unma.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        unma.setText("Un-Married");

        wi.setBackground(new java.awt.Color(0, 153, 153));
        ms.add(wi);
        wi.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        wi.setText("Widowed");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setText("Address:");

        nextp.setBackground(new java.awt.Color(0, 153, 153));
        nextp.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        nextp.setText("Next");
        nextp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextpActionPerformed(evt);
            }
        });

        s.setBackground(new java.awt.Color(0, 204, 204));
        s.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select State-", "Chhattisgarh", "Maharashtra", "Madhya Pradesh", "West Bengal" }));
        s.setToolTipText("");
        s.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sItemStateChanged(evt);
            }
        });

        t.setBackground(new java.awt.Color(0, 204, 204));
        t.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        t.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Taluka-" }));
        t.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tItemStateChanged(evt);
            }
        });

        v.setBackground(new java.awt.Color(0, 204, 204));
        v.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        v.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Village-" }));

        c_no1.setBackground(new java.awt.Color(0, 204, 204));
        c_no1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        c_no1.setText("10 Digit Contact Number");
        c_no1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_no1MouseClicked(evt);
            }
        });

        g_wrong.setText("Select GENDER");

        d.setBackground(new java.awt.Color(0, 204, 204));
        d.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select District-" }));
        d.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout personalLayout = new javax.swing.GroupLayout(personal);
        personal.setLayout(personalLayout);
        personalLayout.setHorizontalGroup(
            personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalLayout.createSequentialGroup()
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel11))
                    .addGroup(personalLayout.createSequentialGroup()
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personalLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addGap(92, 92, 92)))
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(c_no1)
                                .addComponent(a_no, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(personalLayout.createSequentialGroup()
                                .addComponent(m)
                                .addGap(18, 18, 18)
                                .addComponent(f))
                            .addGroup(personalLayout.createSequentialGroup()
                                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(personalLayout.createSequentialGroup()
                                            .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)
                                            .addComponent(m_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalLayout.createSequentialGroup()
                                            .addComponent(ma)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(unma)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(personalLayout.createSequentialGroup()
                                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)))
                                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wi)
                                    .addGroup(personalLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(g_wrong)
                                            .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nextp)
                .addGap(369, 369, 369))
        );
        personalLayout.setVerticalGroup(
            personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(m_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(m)
                        .addComponent(f)
                        .addComponent(g_wrong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_no))
                .addGap(18, 18, 18)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(c_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unma)))
                .addGap(18, 18, 18)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextp)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        add_detail.addTab("Personal Details", personal);

        income.setBackground(new java.awt.Color(0, 153, 153));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel13.setText("Income Per Annum");

        inc_get.setBackground(new java.awt.Color(0, 204, 204));
        inc_get.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        inc_get.setText("Enter Income Per Annum");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setText("Ration Card Type");

        inc_grp.setBackground(new java.awt.Color(0, 204, 204));
        inc_grp.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        inc_grp.setText("Your Income Group");
        inc_grp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inc_grpActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel15.setText("Income Details");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel18.setText("Income Group");

        poc.setBackground(new java.awt.Color(0, 153, 153));
        poc.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        poc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Tehsildar Report", "Income Annexure II", "EWS Certificate" }));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel19.setText("Proof of Income");

        type1.setBackground(new java.awt.Color(0, 153, 153));
        type1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        type1.setText("Blue/Pink/Red/White");

        type2.setBackground(new java.awt.Color(0, 153, 153));
        type2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        type2.setText("Orange");

        type3.setBackground(new java.awt.Color(0, 153, 153));
        type3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        type3.setText("Yellow");

        nexti.setBackground(new java.awt.Color(0, 153, 153));
        nexti.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        nexti.setText("Next");
        nexti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout incomeLayout = new javax.swing.GroupLayout(income);
        income.setLayout(incomeLayout);
        incomeLayout.setHorizontalGroup(
            incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeLayout.createSequentialGroup()
                .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(incomeLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel15))
                    .addGroup(incomeLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(24, 24, 24)
                        .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inc_grp)
                                .addComponent(inc_get)
                                .addComponent(poc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(incomeLayout.createSequentialGroup()
                                .addComponent(type1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(type2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(type3))))
                    .addGroup(incomeLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(nexti)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        incomeLayout.setVerticalGroup(
            incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inc_get, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inc_grp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(incomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type1)
                    .addComponent(type2)
                    .addComponent(type3))
                .addGap(56, 56, 56)
                .addComponent(nexti)
                .addGap(317, 317, 317))
        );

        add_detail.addTab("Income Details", income);

        doc.setBackground(new java.awt.Color(0, 153, 153));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel10.setText("Applicant Document List");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel20.setText("Aadhar Card");

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel21.setText("Status");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel22.setText("Document Name");

        acy.setBackground(new java.awt.Color(0, 153, 153));
        acy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        acy.setText("Submitted");

        acn.setBackground(new java.awt.Color(0, 153, 153));
        acn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        acn.setText("Not Submitted");

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel23.setText("Marriage Certificate");

        mcy.setBackground(new java.awt.Color(0, 153, 153));
        mcy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcy.setText("Submitted");

        mcn.setBackground(new java.awt.Color(0, 153, 153));
        mcn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcn.setText("Not Submitted");

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel24.setText("Birth Certificate");

        bcy.setBackground(new java.awt.Color(0, 153, 153));
        bcy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bcy.setText("Submitted");

        bcn.setBackground(new java.awt.Color(0, 153, 153));
        bcn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bcn.setText("Not Submitted");

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel25.setText("Income Certificate");

        icy.setBackground(new java.awt.Color(0, 153, 153));
        icy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        icy.setText("Submitted");

        icn.setBackground(new java.awt.Color(0, 153, 153));
        icn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        icn.setText("Not Submitted");

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel26.setText("(if applicable)");

        submit.setBackground(new java.awt.Color(0, 153, 153));
        submit.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit.setMnemonic('S');
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel27.setText("Ration Card ");

        mcy1.setBackground(new java.awt.Color(0, 153, 153));
        mcy1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcy1.setText("Submitted");

        mcn1.setBackground(new java.awt.Color(0, 153, 153));
        mcn1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcn1.setText("Not Submitted");

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(189, 32, 49));
        jLabel28.setText("*");

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(189, 32, 49));
        jLabel29.setText("*");

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(189, 32, 49));
        jLabel30.setText("*");

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(189, 32, 49));
        jLabel31.setText("*");

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(189, 32, 49));
        jLabel32.setText("*");

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel33.setText(" are Compulsory.");

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel34.setText("Note - Documents marked with ");

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel35.setText("Death Certificate");

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel36.setText("(for widowed applicant only)");

        mcy2.setBackground(new java.awt.Color(0, 153, 153));
        mcy2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcy2.setText("Submitted");

        mcn2.setBackground(new java.awt.Color(0, 153, 153));
        mcn2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcn2.setText("Not Submitted");

        javax.swing.GroupLayout docLayout = new javax.swing.GroupLayout(doc);
        doc.setLayout(docLayout);
        docLayout.setHorizontalGroup(
            docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(docLayout.createSequentialGroup()
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(docLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel10))
                    .addGroup(docLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel34)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel32)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel33)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(docLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel23)
                    .addGroup(docLayout.createSequentialGroup()
                        .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel20)
                            .addGroup(docLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(7, 7, 7))
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29)))
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(docLayout.createSequentialGroup()
                        .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acy)
                            .addComponent(mcy)
                            .addComponent(bcy)
                            .addComponent(icy)
                            .addComponent(mcy1)
                            .addComponent(mcy2))
                        .addGap(46, 46, 46)
                        .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mcn1)
                            .addComponent(icn)
                            .addComponent(mcn)
                            .addComponent(acn)
                            .addComponent(bcn)
                            .addComponent(mcn2))))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, docLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(332, 332, 332))
        );
        docLayout.setVerticalGroup(
            docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(docLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(52, 52, 52)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(7, 7, 7)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bcy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bcn))
                    .addGroup(docLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icn)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mcy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mcn1))
                    .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mcn)
                        .addComponent(mcy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcy)
                    .addComponent(mcn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(submit)
                .addGap(41, 41, 41)
                .addGroup(docLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(170, 170, 170))
        );

        add_detail.addTab("Document List", doc);

        getContentPane().add(add_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, 780));

        view.setBackground(new java.awt.Color(0, 153, 153));
        view.setMaximumSize(new java.awt.Dimension(870, 780));
        view.setMinimumSize(new java.awt.Dimension(870, 780));
        view.setPreferredSize(new java.awt.Dimension(870, 780));

        view_main.setBackground(new java.awt.Color(0, 153, 153));
        view_main.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        view_main.setText("get");
        view_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_mainActionPerformed(evt);
            }
        });

        app_no1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        app_no1.setText("Label");

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(app_no1)
                .addGap(245, 245, 245)
                .addComponent(view_main, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(app_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_main, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(712, 712, 712))
        );

        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        view1.setBackground(new java.awt.Color(0, 153, 153));
        view1.setMaximumSize(new java.awt.Dimension(870, 780));
        view1.setMinimumSize(new java.awt.Dimension(870, 780));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel40.setText("Name:");

        f_name2.setBackground(new java.awt.Color(0, 204, 204));
        f_name2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        f_name2.setText("First Name");
        f_name2.setMinimumSize(new java.awt.Dimension(99, 32));
        f_name2.setName(""); // NOI18N

        m_name2.setBackground(new java.awt.Color(0, 204, 204));
        m_name2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        m_name2.setText("Middle Name");
        m_name2.setMinimumSize(new java.awt.Dimension(99, 32));
        m_name2.setName(""); // NOI18N

        l_name2.setBackground(new java.awt.Color(0, 204, 204));
        l_name2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        l_name2.setText("Last Name");
        l_name2.setMinimumSize(new java.awt.Dimension(99, 32));
        l_name2.setName(""); // NOI18N

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel41.setText("Gender:");

        jLabel48.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel48.setText("Marital Status:");

        jLabel49.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel49.setText("Address:");

        gen1.setBackground(new java.awt.Color(0, 204, 204));
        gen1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        gen1.setText("First Name");
        gen1.setMinimumSize(new java.awt.Dimension(99, 32));
        gen1.setName(""); // NOI18N

        ms2.setBackground(new java.awt.Color(0, 204, 204));
        ms2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ms2.setText("Your Age");

        v2.setBackground(new java.awt.Color(0, 204, 204));
        v2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        v2.setText("12 Digit Aadhar Number");

        d2.setBackground(new java.awt.Color(0, 204, 204));
        d2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        d2.setText("12 Digit Aadhar Number");

        s2.setBackground(new java.awt.Color(0, 204, 204));
        s2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        s2.setText("12 Digit Aadhar Number");

        t2.setBackground(new java.awt.Color(0, 204, 204));
        t2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        t2.setText("12 Digit Aadhar Number");

        jLabel50.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel50.setText("Income Per Annum");

        inc1.setBackground(new java.awt.Color(0, 204, 204));
        inc1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        inc1.setText("12 Digit Aadhar Number");

        view_sub.setBackground(new java.awt.Color(0, 153, 153));
        view_sub.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        view_sub.setText("get");
        view_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_subActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel51.setText("Details");

        app_no2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        app_no2.setText("Label");

        javax.swing.GroupLayout view1Layout = new javax.swing.GroupLayout(view1);
        view1.setLayout(view1Layout);
        view1Layout.setHorizontalGroup(
            view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view1Layout.createSequentialGroup()
                        .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel48)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addGroup(view1Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(46, 46, 46)))
                        .addGap(51, 51, 51)
                        .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(view1Layout.createSequentialGroup()
                                .addComponent(s2)
                                .addGap(90, 90, 90))
                            .addComponent(d2)
                            .addComponent(t2)
                            .addComponent(v2)
                            .addGroup(view1Layout.createSequentialGroup()
                                .addComponent(ms2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(view1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gen1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(view1Layout.createSequentialGroup()
                                        .addComponent(f_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(m_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(l_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(3, 3, 3))
                    .addGroup(view1Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(18, 18, 18)
                        .addComponent(inc1))
                    .addGroup(view1Layout.createSequentialGroup()
                        .addComponent(app_no2)
                        .addGap(245, 245, 245)
                        .addComponent(view_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
            .addGroup(view1Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel51)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        view1Layout.setVerticalGroup(
            view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(app_no2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_sub, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(f_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m_name2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(gen1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(s2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(272, 272, 272))
        );

        getContentPane().add(view1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_detActionPerformed
 view1.setVisible(false);
    app_home.setVisible(false);     // TODO add your handling code here:
    view.setVisible(false);
    add_detail.setVisible(true);
    }//GEN-LAST:event_add_detActionPerformed

    private void view_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_detActionPerformed
    add_detail.setVisible(false);
    app_home.setVisible(false);
    view1.setVisible(false);
    view.setVisible(false);
    view.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_view_detActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
    add_detail.setVisible(false);
    app_home.setVisible(true);
    view1.setVisible(false);
    view.setVisible(false);
             
// TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        this.setVisible(false);
       login re = new login();
       re.setVisible(true);  
                
// TODO add your handling code here:
    }//GEN-LAST:event_log_outActionPerformed

    private void f_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_nameMouseClicked
        g_wrong.setVisible(false);
        f_name.setText("");
        f_name.setBackground(Color.green);
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameMouseClicked

    private void m_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_nameMouseClicked
        g_wrong.setVisible(false);
        m_name.setText("");
        if(!(f_name.getText().matches("[A-Z][a-z]*" )) || (f_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            f_name.setBackground(Color.red);
        }
        else
        {
            f_name.setBackground(Color.green);
        }
    }//GEN-LAST:event_m_nameMouseClicked

    private void l_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_nameMouseClicked
        g_wrong.setVisible(false);
        l_name.setText("");
        if(!(f_name.getText().matches("[A-Z][a-z]*" )) || (f_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            f_name.setBackground(Color.red);
            l_name.setBackground(Color.red);
        }
        else if(!(m_name.getText().matches("[A-Z][a-z]*" )) || (m_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            l_name.setBackground(Color.red);
        }

        else
        {
            m_name.setBackground(Color.GREEN);
            f_name.setBackground(Color.green);// TODO add your handling code here:
        }
    }//GEN-LAST:event_l_nameMouseClicked

    private void mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMouseClicked
        g_wrong.setVisible(false);
        if(!(f_name.getText().matches("[A-Z][a-z]*" )) || (f_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            f_name.setBackground(Color.red);
            l_name.setBackground(Color.red);
        }
        else if(!(m_name.getText().matches("[A-Z][a-z]*" )) || (m_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            l_name.setBackground(Color.red);
        }
        else if(!(l_name.getText().matches("[A-Z][a-z]*" )) || (l_name.getText().matches("")))
        {
            l_name.setBackground(Color.red);
        }
        else
        {
            m_name.setBackground(Color.GREEN);
            f_name.setBackground(Color.green);
            l_name.setBackground(Color.GREEN);

        }
    }//GEN-LAST:event_mMouseClicked

    private void fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fMouseClicked
        g_wrong.setVisible(false);
        if(!(f_name.getText().matches("[A-Z][a-z]*" )) || (f_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            f_name.setBackground(Color.red);
            l_name.setBackground(Color.red);
        }
        else if(!(m_name.getText().matches("[A-Z][a-z]*" )) || (m_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            l_name.setBackground(Color.red);
        }
        else if(!(l_name.getText().matches("[A-Z][a-z]*" )) || (l_name.getText().matches("")))
        {
            l_name.setBackground(Color.red);
        }
        else
        {
            m_name.setBackground(Color.GREEN);
            f_name.setBackground(Color.green);
            l_name.setBackground(Color.GREEN);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_fMouseClicked

    private void a_noMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_noMouseClicked
        g_wrong.setVisible(false);
        a_no.setText("");
        if(!(f_name.getText().matches("[A-Z][a-z]*" )) || (f_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            f_name.setBackground(Color.red);
            l_name.setBackground(Color.red);
            f.setBackground(Color.red);
            m.setBackground(Color.red);
            g_wrong.setVisible(true);
        }
        else if(!(m_name.getText().matches("[A-Z][a-z]*" )) || (m_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            l_name.setBackground(Color.red);
            f.setBackground(Color.red);
            m.setBackground(Color.red);
            g_wrong.setVisible(true);
        }
        else if(!(l_name.getText().matches("[A-Z][a-z]*" )) || (l_name.getText().matches("")))
        {
            l_name.setBackground(Color.red);
            f.setBackground(Color.red);
            m.setBackground(Color.red);
            g_wrong.setVisible(true);
        }
        else if(!(g.isSelected(m.getModel())||g.isSelected(f.getModel())))
        {
            l_name.setBackground(Color.green);
            g_wrong.setVisible(true);    }

        else
        {
            m_name.setBackground(Color.GREEN);
            f_name.setBackground(Color.green);
            l_name.setBackground(Color.GREEN);

            g_wrong.setVisible(false);
        }
    }//GEN-LAST:event_a_noMouseClicked

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        Date date = dob.getDate();
     DateFormat oDateFormat = new SimpleDateFormat("dd-MM-yy");
     String szDate = oDateFormat.format(date);
     LocalDate ld = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
     System.out.println(szDate);
     Period p = Period.between( ld , LocalDate.now());
     String aged = Integer.toString(p.getYears());
     System.out.println("Age" + aged);
     System.out.println(p.getYears());
     age.setText(aged);

        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void c_no1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_no1MouseClicked
        if(!(f_name.getText().matches("[A-Z][a-z]*" )) || (f_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            f_name.setBackground(Color.red);
            l_name.setBackground(Color.red);

            a_no.setBackground(Color.red);
        }
        else if(!(m_name.getText().matches("[A-Z][a-z]*" )) || (m_name.getText().matches("")))
        {
            m_name.setBackground(Color.RED);
            l_name.setBackground(Color.red);
            a_no.setBackground(Color.red);
        }
        else if(!(l_name.getText().matches("[A-Z][a-z]*" )) || (l_name.getText().matches("")))
        {
            l_name.setBackground(Color.red);
            a_no.setBackground(Color.red);
        }
        else if(!(g.isSelected(m.getModel())||g.isSelected(f.getModel())))
        {
            a_no.setBackground(Color.red);
            g_wrong.setVisible(true);
        }
        else if(!(a_no.getText().matches("[0-9]*{12}")))
        {
            a_no.setBackground(Color.red);
        }
        else
        {
            m_name.setBackground(Color.GREEN);
            f_name.setBackground(Color.green);
            l_name.setBackground(Color.GREEN);
            g_wrong.setVisible(false);
            a_no.setBackground(Color.green);
        } // TODO add your handling code here:
    }//GEN-LAST:event_c_no1MouseClicked

    private void inc_grpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inc_grpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inc_grpActionPerformed

    private void nextiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextiActionPerformed
add_detail.setSelectedIndex(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_nextiActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        conn c = new conn();
        con=c.getconn();
        String query = "Insert into app_table_name (f_name,m_name,l_name,village,taluka,district,state,gender,marital_status) values(?,?,?,?,?,?,?,?,?)" ;
        try
        {
            pst = con.prepareStatement(query);
        
            pst.setString(1,f_name.getText());
            pst.setString(2, m_name.getText());
            pst.setString(3,l_name.getText());
            pst.setString(4, v.getSelectedItem().toString());
            pst.setString(5, t.getSelectedItem().toString());
            pst.setString(6, d.getSelectedItem().toString());
            pst.setString(7, s.getSelectedItem().toString());
            pst.setString(8, g.getSelection().toString());
            pst.setString(9, ms.getSelection().toString());

            pst.execute();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void view_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_mainActionPerformed
        view.setVisible(false);
        try {
        conn c = new conn();
        con=c.getconn();
        st = con.createStatement();
        String sql = "SELECT first_name,middle_name,Gender,last_name,Maratial_status,state,district,taluka,village,Annual_Income FROM APPLICANTS WHERE  Appl_no = 11 ";
        rs = st.executeQuery(sql);
    while(rs.next()) { 
        
        f_name2.setText(rs.getString("first_name"));
        m_name2.setText(rs.getString("middle_name"));
       gen1.setText(rs.getString("Gender")); 
        l_name2.setText(rs.getString("last_name"));
        ms2.setText(rs.getString("Maratial_status"));
       s2.setText(rs.getString("state"));
        d2.setText(rs.getString("district"));
        t2.setText(rs.getString("taluka"));
        v2.setText(rs.getString("village"));
        inc1.setText(rs.getString("Annual_Income"));


    }
    } catch (SQLException e ) {
    JOptionPane.showMessageDialog(null, e); 

    }    
            view1.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_view_mainActionPerformed
    
    
    private void nextpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextpActionPerformed
    add_detail.setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_nextpActionPerformed

    private void sItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sItemStateChanged
        if(s.getSelectedItem().toString().equalsIgnoreCase("Maharashtra"))
        {
            d.removeAllItems();
            d.addItem("Buldhana");
            d.addItem("Nashik");
            d.addItem("Dhule");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("Chhattisgarh"))
        {
            d.removeAllItems();
            d.addItem("Bilaspur");
            d.addItem("Korba");
            d.addItem("Raipur");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("West Bengal"))
        {
            d.removeAllItems();
            d.addItem("Hoogly");
            d.addItem("Birbhum");
            d.addItem("South 24 Parganas");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("Madhya pradesh"))
        {
            d.removeAllItems();
            d.addItem("Dhar");
            d.addItem("Guna");
            d.addItem("Panna");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_sItemStateChanged

    private void dItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dItemStateChanged
        if(d.getSelectedItem().toString().equalsIgnoreCase("Buldhana"))
        {
            t.removeAllItems();
            t.addItem("Deulgaon Raja");
            t.addItem("Lonar");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            t.removeAllItems();
            t.addItem("Nashik");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Dhule"))
        {
            t.removeAllItems();
            t.addItem("Shirpur");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Bilaspur"))
        {
            t.removeAllItems();
            t.addItem("Marwani");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Korba"))
        {
            t.removeAllItems();
            t.addItem("Pali");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Raipur"))
        {
            t.removeAllItems();
            t.addItem("Arang");
            t.addItem("Tilda");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Hoogly"))
        {
            t.removeAllItems();
            t.addItem("Haripal");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Birbhum"))
        {
            t.removeAllItems();
            t.addItem("Nanoor");
            t.addItem("Labpur");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("South 24 Paraganas"))
        {
            t.removeAllItems();
            t.addItem("Kulpi");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Dhar"))
        {
            t.removeAllItems();
            t.addItem("Bagh");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Guna"))
        {
            t.removeAllItems();
            t.addItem("Aron");
            t.addItem("Chanchoda");
            t.addItem("Bamori");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Panna"))
        {
            t.removeAllItems();
            t.addItem("Gunor");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dItemStateChanged

    private void tItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tItemStateChanged
        if(t.getSelectedItem().toString().equalsIgnoreCase("Deulgaon Raja"))
        {
            v.removeAllItems();
            v.addItem("Aaland");
            v.addItem("Umbarkhed");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Lonar"))
        {
            v.removeAllItems();
            v.addItem("Hirdav");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            v.removeAllItems();
            v.addItem("Matori");
            v.addItem("Dari");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Shirpur"))
        {
            v.removeAllItems();
            v.addItem("Jalod");
            v.addItem("Mandal");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Marwahi"))
        {
            v.removeAllItems();
            v.addItem("Dhanpur");
            v.addItem("Lohari");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Pali"))
        {
            v.removeAllItems();
            v.addItem("Batra");
            v.addItem("Sirli");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Arang"))
        {
            v.removeAllItems();
            v.addItem("Ameri");
            v.addItem("Nisda");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Haripal"))
        {
            v.removeAllItems();
            v.addItem("Kaikala");
            v.addItem("Jejur");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Nanoor"))
        {
            v.removeAllItems();
            v.addItem("Thupsara");
            v.addItem("Jalundi");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Kulpi"))
        {
            v.removeAllItems();
            v.addItem("Dhola");
            v.addItem("Ramkishore");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Bagh"))
        {
            v.removeAllItems();
            v.addItem("Devdha");
            v.addItem("Jali");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Aron"))
        {
            v.removeAllItems();
            v.addItem("Davri");
            v.addItem("Patan");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Gunor"))
        {
            v.removeAllItems();
            v.addItem("Ganj");
            v.addItem("Kamtana");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Tilda"))
        {
            v.removeAllItems();
            v.addItem("Bhiloni");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Labpur"))
        {
            v.removeAllItems();
            v.addItem("Jamna");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Chanchoda"))
        {
            v.removeAllItems();
            v.addItem("Murela");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Bamori"))
        {
            v.removeAllItems();
            v.addItem("Rampur");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tItemStateChanged

    private void view_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_subActionPerformed
          try {
        conn c = new conn();
        con=c.getconn();
        st = con.createStatement();
        String sql = "SELECT first_name,middle_name,Gender,last_name,Maratial_status,state,district,taluka,village,Annual_Income FROM APPLICANTS WHERE  Appl_no = 11 ";
        rs = st.executeQuery(sql);
    while(rs.next()) { 
        
        f_name2.setText(rs.getString("first_name"));
        m_name2.setText(rs.getString("middle_name"));
       gen1.setText(rs.getString("Gender")); 
        l_name2.setText(rs.getString("last_name"));
        ms2.setText(rs.getString("Maratial_status"));
       s2.setText(rs.getString("state"));
        d2.setText(rs.getString("district"));
        t2.setText(rs.getString("taluka"));
        v2.setText(rs.getString("village"));
        inc1.setText(rs.getString("Annual_Income"));


    }
    } catch (SQLException e ) {
    JOptionPane.showMessageDialog(null, e); 

    }    
            view1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_view_subActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicant_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicant_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicant_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicant_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applicant_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_no;
    private javax.swing.JRadioButton acn;
    private javax.swing.JRadioButton acy;
    private javax.swing.JButton add_det;
    private javax.swing.JTabbedPane add_detail;
    private javax.swing.JTextField age;
    private javax.swing.JPanel app_home;
    private javax.swing.JLabel app_no;
    private javax.swing.JLabel app_no1;
    private javax.swing.JLabel app_no2;
    private javax.swing.JRadioButton bcn;
    private javax.swing.JRadioButton bcy;
    private javax.swing.JTextField c_no1;
    private javax.swing.JComboBox<String> d;
    private javax.swing.JTextField d2;
    private org.jdesktop.swingx.JXDatePicker dob;
    private javax.swing.JPanel doc;
    private javax.swing.JRadioButton f;
    private javax.swing.JTextField f_name;
    private javax.swing.JTextField f_name2;
    private javax.swing.ButtonGroup g;
    private javax.swing.JLabel g_wrong;
    private javax.swing.JTextField gen1;
    private javax.swing.JButton home;
    private javax.swing.JRadioButton icn;
    private javax.swing.JRadioButton icy;
    private javax.swing.JTextField inc1;
    private javax.swing.JTextField inc_get;
    private javax.swing.JTextField inc_grp;
    private javax.swing.JPanel income;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField l_name;
    private javax.swing.JTextField l_name2;
    private javax.swing.JButton log_out;
    private javax.swing.JRadioButton m;
    private javax.swing.JTextField m_name;
    private javax.swing.JTextField m_name2;
    private javax.swing.JRadioButton ma;
    private javax.swing.JRadioButton mcn;
    private javax.swing.JRadioButton mcn1;
    private javax.swing.JRadioButton mcn2;
    private javax.swing.JRadioButton mcy;
    private javax.swing.JRadioButton mcy1;
    private javax.swing.JRadioButton mcy2;
    private javax.swing.ButtonGroup ms;
    private javax.swing.JTextField ms2;
    private javax.swing.JButton nexti;
    private javax.swing.JButton nextp;
    private javax.swing.JPanel personal;
    private javax.swing.JComboBox<String> poc;
    private javax.swing.JComboBox<String> s;
    private javax.swing.JTextField s2;
    private javax.swing.JButton submit;
    private javax.swing.JComboBox<String> t;
    private javax.swing.JTextField t2;
    private javax.swing.JRadioButton type1;
    private javax.swing.JRadioButton type2;
    private javax.swing.JRadioButton type3;
    private javax.swing.JRadioButton unma;
    private javax.swing.JComboBox<String> v;
    private javax.swing.JTextField v2;
    private javax.swing.JPanel view;
    private javax.swing.JPanel view1;
    private javax.swing.JButton view_det;
    private javax.swing.JButton view_main;
    private javax.swing.JButton view_sub;
    private javax.swing.JRadioButton wi;
    // End of variables declaration//GEN-END:variables
}
