/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rural_housing;

import java.awt.Color;
import java.math.BigInteger;
import java.sql.*;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhik
 */
public class applicant_main extends javax.swing.JFrame {
Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement st = null;
    /**
     * Creates new form applicant_main
     */
    public applicant_main() {
            conn c = new conn();
        con=c.getconn();
    
        initComponents();
   doc1.setVisible(false);
    view.setVisible(false);
    app_home.setVisible(true);
        ac.add(acy2);
        ac.add(acn2);
        bc.add(bcy2);
        bc.add(bcn2);
        ic.add(icy2);
        ic.add(icn2);
        rc.add(rcy2);
        rc.add(rcy2);
        mc.add(dcy2);
        mc.add(mcn2);
        dc.add(dcy2);
        dc.add(dcn2);
        
            dcn2.setEnabled(false);
            dcy2.setEnabled(false);
            mcn2.setEnabled(false);
            mcy2.setEnabled(false);
    view1.setVisible(false);
    }

    public applicant_main(String abc) {
    initComponents();
    conn c = new conn();
    con=c.getconn();
    app_no.setText(abc);
    app_no1.setText(abc);
    app_no2.setText(abc);
     app_no3.setText(abc);
   doc1.setVisible(false);
    view.setVisible(false);
    app_home.setVisible(true);
    view1.setVisible(false);
    ac.add(acy2);
        ac.add(acn2);
        bc.add(bcy2);
        bc.add(bcn2);
        ic.add(icy2);
        ic.add(icn2);
        rc.add(rcy2);
        rc.add(rcn2);
        mc.add(mcy2);
        mc.add(mcn2);
        dc.add(dcy2);
        dc.add(dcn2);
        
            dcn2.setEnabled(true);
            dcy2.setEnabled(true);
            mcn2.setEnabled(true);
            mcy2.setEnabled(true);
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g = new javax.swing.ButtonGroup();
        ms = new javax.swing.ButtonGroup();
        ac = new javax.swing.ButtonGroup();
        bc = new javax.swing.ButtonGroup();
        ic = new javax.swing.ButtonGroup();
        rc = new javax.swing.ButtonGroup();
        mc = new javax.swing.ButtonGroup();
        dc = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        app_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        app_no = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        add_det = new javax.swing.JButton();
        view_det = new javax.swing.JButton();
        home = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        view = new javax.swing.JPanel();
        view_main = new javax.swing.JButton();
        app_no1 = new javax.swing.JLabel();
        view1 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        f_name2 = new javax.swing.JTextField();
        m_name2 = new javax.swing.JTextField();
        l_name2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        a_no1 = new javax.swing.JTextField();
        ms2 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        inc1 = new javax.swing.JTextField();
        view_sub = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        app_no2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        gen1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        c_no = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        dob1 = new javax.swing.JTextField();
        age1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        inc2 = new javax.swing.JTextField();
        doc1 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        acy2 = new javax.swing.JRadioButton();
        acn2 = new javax.swing.JRadioButton();
        jLabel70 = new javax.swing.JLabel();
        dcy2 = new javax.swing.JRadioButton();
        mcn2 = new javax.swing.JRadioButton();
        jLabel71 = new javax.swing.JLabel();
        bcy2 = new javax.swing.JRadioButton();
        bcn2 = new javax.swing.JRadioButton();
        jLabel72 = new javax.swing.JLabel();
        icy2 = new javax.swing.JRadioButton();
        icn2 = new javax.swing.JRadioButton();
        jLabel73 = new javax.swing.JLabel();
        submit2 = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        rcy2 = new javax.swing.JRadioButton();
        rcn2 = new javax.swing.JRadioButton();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        mcy2 = new javax.swing.JRadioButton();
        dcn2 = new javax.swing.JRadioButton();
        app_no3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 960));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rural_housing/Logo.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(330, 330, 330))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 180));

        app_home.setBackground(new java.awt.Color(0, 153, 153));
        app_home.setMaximumSize(new java.awt.Dimension(880, 780));
        app_home.setMinimumSize(new java.awt.Dimension(880, 780));
        app_home.setPreferredSize(new java.awt.Dimension(880, 780));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 29)); // NOI18N
        jLabel2.setText("Welcome To Rural Housing Allocation System.");

        app_no.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        app_no.setText("Label");

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel37.setText("Applicant Login");

        javax.swing.GroupLayout app_homeLayout = new javax.swing.GroupLayout(app_home);
        app_home.setLayout(app_homeLayout);
        app_homeLayout.setHorizontalGroup(
            app_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_homeLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_homeLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(app_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_homeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_homeLayout.createSequentialGroup()
                        .addComponent(app_no)
                        .addGap(403, 403, 403))))
        );
        app_homeLayout.setVerticalGroup(
            app_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_homeLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(app_no, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        getContentPane().add(app_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        add_det.setBackground(new java.awt.Color(0, 204, 204));
        add_det.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        add_det.setMnemonic('U');
        add_det.setText("Update Details");
        add_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_detActionPerformed(evt);
            }
        });

        view_det.setBackground(new java.awt.Color(0, 204, 204));
        view_det.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        view_det.setMnemonic('V');
        view_det.setText("View  Details");
        view_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_detActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 204, 204));
        home.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        home.setMnemonic('H');
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        log_out.setBackground(new java.awt.Color(0, 204, 204));
        log_out.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        log_out.setMnemonic('L');
        log_out.setText("Log Out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setText("Applicant Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel17)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(log_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(view_det, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_det, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_det)
                .addGap(51, 51, 51)
                .addComponent(view_det)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addComponent(home)
                .addGap(50, 50, 50)
                .addComponent(log_out)
                .addGap(83, 83, 83))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, 780));

        view.setBackground(new java.awt.Color(0, 153, 153));
        view.setMaximumSize(new java.awt.Dimension(870, 780));
        view.setMinimumSize(new java.awt.Dimension(870, 780));
        view.setPreferredSize(new java.awt.Dimension(870, 780));

        view_main.setBackground(new java.awt.Color(0, 153, 153));
        view_main.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        view_main.setText("Get Details");
        view_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_mainActionPerformed(evt);
            }
        });

        app_no1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        app_no1.setText("Label");

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(app_no1)
                .addGap(245, 245, 245)
                .addComponent(view_main, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(app_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_main, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(712, 712, 712))
        );

        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        view1.setBackground(new java.awt.Color(0, 153, 153));
        view1.setMaximumSize(new java.awt.Dimension(870, 780));
        view1.setMinimumSize(new java.awt.Dimension(870, 780));
        view1.setPreferredSize(new java.awt.Dimension(870, 780));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel40.setText("Name:");

        f_name2.setEditable(false);
        f_name2.setBackground(new java.awt.Color(0, 204, 204));
        f_name2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        f_name2.setMinimumSize(new java.awt.Dimension(99, 32));
        f_name2.setName(""); // NOI18N

        m_name2.setEditable(false);
        m_name2.setBackground(new java.awt.Color(0, 204, 204));
        m_name2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        m_name2.setMinimumSize(new java.awt.Dimension(99, 32));
        m_name2.setName(""); // NOI18N
        m_name2.setPreferredSize(new java.awt.Dimension(99, 32));
        m_name2.setRequestFocusEnabled(false);

        l_name2.setEditable(false);
        l_name2.setBackground(new java.awt.Color(0, 204, 204));
        l_name2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        l_name2.setMinimumSize(new java.awt.Dimension(99, 32));
        l_name2.setName(""); // NOI18N

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel41.setText("Gender:");

        jLabel48.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel48.setText("Marital Status:");

        jLabel49.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel49.setText("Address:");

        a_no1.setEditable(false);
        a_no1.setBackground(new java.awt.Color(0, 204, 204));
        a_no1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        a_no1.setMinimumSize(new java.awt.Dimension(99, 32));
        a_no1.setName(""); // NOI18N

        ms2.setEditable(false);
        ms2.setBackground(new java.awt.Color(0, 204, 204));
        ms2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ms2.setMinimumSize(new java.awt.Dimension(105, 32));
        ms2.setPreferredSize(new java.awt.Dimension(105, 32));

        v2.setEditable(false);
        v2.setBackground(new java.awt.Color(0, 204, 204));
        v2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        v2.setText(" ");

        d2.setEditable(false);
        d2.setBackground(new java.awt.Color(0, 204, 204));
        d2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        d2.setText(" ");

        s2.setEditable(false);
        s2.setBackground(new java.awt.Color(0, 204, 204));
        s2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        s2.setText(" ");

        t2.setEditable(false);
        t2.setBackground(new java.awt.Color(0, 204, 204));
        t2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        t2.setText(" ");

        jLabel50.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel50.setText("Income Per Annum");

        inc1.setEditable(false);
        inc1.setBackground(new java.awt.Color(0, 204, 204));
        inc1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        view_sub.setBackground(new java.awt.Color(0, 153, 153));
        view_sub.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        view_sub.setText("Get Details");
        view_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_subActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel51.setText("Details");

        app_no2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        app_no2.setText("Label");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setText("Aadhar Number:");

        gen1.setEditable(false);
        gen1.setBackground(new java.awt.Color(0, 204, 204));
        gen1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        gen1.setMinimumSize(new java.awt.Dimension(99, 32));
        gen1.setName(""); // NOI18N

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel38.setText("Contact Number:");

        c_no.setEditable(false);
        c_no.setBackground(new java.awt.Color(0, 204, 204));
        c_no.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        c_no.setMinimumSize(new java.awt.Dimension(99, 32));
        c_no.setName(""); // NOI18N

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel42.setText("DOB:");

        jLabel43.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel43.setText("AGE:");

        dob1.setEditable(false);
        dob1.setBackground(new java.awt.Color(0, 204, 204));
        dob1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dob1.setMinimumSize(new java.awt.Dimension(99, 32));
        dob1.setName(""); // NOI18N

        age1.setEditable(false);
        age1.setBackground(new java.awt.Color(0, 204, 204));
        age1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        age1.setMinimumSize(new java.awt.Dimension(99, 32));
        age1.setName(""); // NOI18N

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel39.setText("Income Group");

        inc2.setEditable(false);
        inc2.setBackground(new java.awt.Color(0, 204, 204));
        inc2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        javax.swing.GroupLayout view1Layout = new javax.swing.GroupLayout(view1);
        view1.setLayout(view1Layout);
        view1Layout.setHorizontalGroup(
            view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view1Layout.createSequentialGroup()
                        .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(view1Layout.createSequentialGroup()
                                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel49)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel38))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createSequentialGroup()
                                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42))
                                .addGap(18, 18, 18)))
                        .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(view1Layout.createSequentialGroup()
                                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(view1Layout.createSequentialGroup()
                                        .addComponent(f_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(m_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(l_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(view1Layout.createSequentialGroup()
                                        .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(view1Layout.createSequentialGroup()
                                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(a_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_no, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86))
                            .addGroup(view1Layout.createSequentialGroup()
                                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gen1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dob1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(view1Layout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(age1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(view1Layout.createSequentialGroup()
                                        .addComponent(jLabel48)
                                        .addGap(18, 18, 18)
                                        .addComponent(ms2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))))
                    .addGroup(view1Layout.createSequentialGroup()
                        .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(view1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(app_no2)
                                .addGap(201, 201, 201)
                                .addComponent(view_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(view1Layout.createSequentialGroup()
                                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel50))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inc1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(inc2))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
            .addGroup(view1Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel51)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        view1Layout.setVerticalGroup(
            view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_sub)
                    .addComponent(app_no2))
                .addGap(9, 9, 9)
                .addComponent(jLabel51)
                .addGap(30, 30, 30)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(f_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(m_name2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gen1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(age1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(c_no, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(view1Layout.createSequentialGroup()
                        .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(inc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(267, 267, 267))
        );

        getContentPane().add(view1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        doc1.setBackground(new java.awt.Color(0, 153, 153));
        doc1.setMaximumSize(new java.awt.Dimension(880, 780));
        doc1.setMinimumSize(new java.awt.Dimension(880, 780));
        doc1.setPreferredSize(new java.awt.Dimension(880, 780));
        doc1.setRequestFocusEnabled(false);

        jLabel66.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel66.setText("Applicant Document List");

        jLabel67.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel67.setText("Aadhar Card");

        jLabel68.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel68.setText("Status");

        jLabel69.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel69.setText("Document Name");

        acy2.setBackground(new java.awt.Color(0, 153, 153));
        acy2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        acy2.setText("Submitted");

        acn2.setBackground(new java.awt.Color(0, 153, 153));
        acn2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        acn2.setText("Not Submitted");

        jLabel70.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel70.setText("Marriage Certificate");

        dcy2.setBackground(new java.awt.Color(0, 153, 153));
        dcy2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        dcy2.setText("Submitted");

        mcn2.setBackground(new java.awt.Color(0, 153, 153));
        mcn2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcn2.setText("Not Submitted");

        jLabel71.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel71.setText("Birth Certificate");

        bcy2.setBackground(new java.awt.Color(0, 153, 153));
        bcy2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bcy2.setText("Submitted");

        bcn2.setBackground(new java.awt.Color(0, 153, 153));
        bcn2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bcn2.setText("Not Submitted");

        jLabel72.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel72.setText("Income Certificate");

        icy2.setBackground(new java.awt.Color(0, 153, 153));
        icy2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        icy2.setText("Submitted");

        icn2.setBackground(new java.awt.Color(0, 153, 153));
        icn2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        icn2.setText("Not Submitted");

        jLabel73.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel73.setText("(if applicable)");

        submit2.setBackground(new java.awt.Color(0, 153, 153));
        submit2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit2.setMnemonic('S');
        submit2.setText("SUBMIT");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel74.setText("Ration Card ");

        rcy2.setBackground(new java.awt.Color(0, 153, 153));
        rcy2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        rcy2.setText("Submitted");

        rcn2.setBackground(new java.awt.Color(0, 153, 153));
        rcn2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        rcn2.setText("Not Submitted");

        jLabel75.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(189, 32, 49));
        jLabel75.setText("*");

        jLabel76.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(189, 32, 49));
        jLabel76.setText("*");

        jLabel77.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(189, 32, 49));
        jLabel77.setText("*");

        jLabel78.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(189, 32, 49));
        jLabel78.setText("*");

        jLabel79.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(189, 32, 49));
        jLabel79.setText("*");

        jLabel80.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel80.setText(" are Compulsory.");

        jLabel81.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel81.setText("Note - Documents marked with ");

        jLabel82.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel82.setText("Death Certificate");

        jLabel83.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel83.setText("(for widowed applicant only)");

        mcy2.setBackground(new java.awt.Color(0, 153, 153));
        mcy2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcy2.setText("Submitted");

        dcn2.setBackground(new java.awt.Color(0, 153, 153));
        dcn2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        dcn2.setText("Not Submitted");

        app_no3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        app_no3.setText("Label");

        javax.swing.GroupLayout doc1Layout = new javax.swing.GroupLayout(doc1);
        doc1.setLayout(doc1Layout);
        doc1Layout.setHorizontalGroup(
            doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doc1Layout.createSequentialGroup()
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doc1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel82)
                            .addComponent(jLabel70)
                            .addGroup(doc1Layout.createSequentialGroup()
                                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel74)
                                    .addComponent(jLabel73)
                                    .addComponent(jLabel67)
                                    .addComponent(jLabel71)
                                    .addComponent(jLabel72))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel75)
                                    .addComponent(jLabel78)
                                    .addComponent(jLabel77)
                                    .addComponent(jLabel76)))
                            .addComponent(jLabel83)
                            .addComponent(jLabel69))
                        .addGap(60, 60, 60)
                        .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel68)
                            .addGroup(doc1Layout.createSequentialGroup()
                                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(acy2)
                                    .addComponent(dcy2)
                                    .addComponent(bcy2)
                                    .addComponent(icy2)
                                    .addComponent(rcy2)
                                    .addComponent(mcy2))
                                .addGap(46, 46, 46)
                                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rcn2)
                                    .addComponent(icn2)
                                    .addComponent(mcn2)
                                    .addComponent(acn2)
                                    .addComponent(bcn2)
                                    .addComponent(dcn2)))))
                    .addGroup(doc1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(app_no3)
                        .addGap(194, 194, 194)
                        .addComponent(jLabel66))
                    .addGroup(doc1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel81)
                        .addGap(0, 0, 0)
                        .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submit2)
                            .addGroup(doc1Layout.createSequentialGroup()
                                .addComponent(jLabel79)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel80)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        doc1Layout.setVerticalGroup(
            doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doc1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(app_no3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(jLabel68))
                .addGap(7, 7, 7)
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel75))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bcy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bcn2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doc1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel71, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel76, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icn2)
                    .addComponent(jLabel77))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rcy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rcn2))
                    .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel78)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mcn2)
                        .addComponent(mcy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcy2)
                    .addComponent(dcn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel83)
                .addGap(71, 71, 71)
                .addComponent(submit2)
                .addGap(39, 39, 39)
                .addGroup(doc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel79)
                    .addComponent(jLabel80)
                    .addComponent(jLabel81))
                .addGap(170, 170, 170))
        );

        getContentPane().add(doc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_detActionPerformed
 view1.setVisible(false);
    app_home.setVisible(false);     // TODO add your handling code here:
    view.setVisible(false);
   doc1.setVisible(true);
   
    conn c = new conn();
    con=c.getconn();
   
   String mc_pass,rc_pass,ac_pass,bc_pass,ic_pass,dc_pass;
        String q2 = "select aadhar_copy,birth_cert_copy,income_cert_copy,ration_copy,marriage_copy,death_copy from APPL_DOCS_SUBMIT where appl_num='"+app_no.getText()+"'";
        try
        {
                st = con.createStatement();
                rs = st.executeQuery(q2);
              
                while(rs.next()) 
                { 
                    ac_pass = (rs.getString("aadhar_copy"));
                    bc_pass = (rs.getString("birth_cert_copy"));
                    ic_pass = (rs.getString("income_cert_copy")); 
                    rc_pass = (rs.getString("ration_copy"));
                    mc_pass = (rs.getString("marriage_copy"));
                    dc_pass = (rs.getString("death_copy"));  
                    System.out.println(ac_pass+"\n"+bc_pass+"\n"+ic_pass+"\n"+rc_pass+"\n"+mc_pass+"\n"+dc_pass+"\n");
    
                    if(ac_pass.equalsIgnoreCase("YES"))
                    {
                       acy2.setSelected(true);
                       System.out.print("acy2");
                    }
                    else
                    {
                       acn2.setSelected(true);
                       System.out.print("acn2");
                    }
                    if(bc_pass.equalsIgnoreCase("YES"))
                    {
                        bcy2.setSelected(true);
                                   System.out.print("bcy2");
                    }
                    else
                    {
                       bcn2.setSelected(true);
                                  System.out.print("bcn2");
                    }
                    if(ic_pass.equalsIgnoreCase("YES"))
                    {
                        icy2.setSelected(true);
                    }
                    else
                    {
                       icn2.setSelected(true);
                    }
                    if(rc_pass.equalsIgnoreCase("YES"))
                    {
                        rcy2.setSelected(true);
                    }
                    else
                    {
                       rcn2.setSelected(true);
                    }
                    if(mc_pass .equalsIgnoreCase("YES"))
                    {
                        mcn2.setSelected(true);
                    }
                    else if(mc_pass.equalsIgnoreCase("NO"))
                    {
                       mcn2.setSelected(true);
                    }
                    else
                    {
                        mcn2.setEnabled(false);
                        mcy2.setEnabled(false); 
                    }
                    if(dc_pass.equalsIgnoreCase("YES"))
                    {
                        dcy2.setSelected(true);
                    }
                    else if(dc_pass.equalsIgnoreCase("NO"))
                    {
                       dcn2.setSelected(true);
                    }
                    else
                    {
                        dcn2.setEnabled(false);
                        dcy2.setEnabled(false);   
                    }
                }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    
    }//GEN-LAST:event_add_detActionPerformed

    private void view_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_detActionPerformed
   doc1.setVisible(false);
    app_home.setVisible(false);
    view1.setVisible(false);
    view.setVisible(false);
    view.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_view_detActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
   doc1.setVisible(false);
    app_home.setVisible(true);
    view1.setVisible(false);
    view.setVisible(false);
             
// TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        this.setVisible(false);
       login re = new login();
       re.setVisible(true);  
                
// TODO add your handling code here:
    }//GEN-LAST:event_log_outActionPerformed

    private void view_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_mainActionPerformed
        doc1.setVisible(false);
    app_home.setVisible(false);
        view.setVisible(false);
         view1.setVisible(true);
        try {
        conn c = new conn();
        con=c.getconn();
        st = con.createStatement();
        String sql = "SELECT  First_name,Middle_name,Last_name,VILLAGE,TALUKA,DISTRICT,STATE,Income_annum,Gender,Marital_status,DOB,Aadhar_no,Contact FROM APPLICANTS WHERE Applicant_no = '"+app_no1.getText()+"'";
        rs = st.executeQuery(sql);
    while(rs.next())
    {   
        c_no.setText(rs.getString("Contact"));
        a_no1.setText(rs.getString("Aadhar_no"));
        f_name2.setText(rs.getString("First_name"));
        m_name2.setText(rs.getString("Middle_name"));
        l_name2.setText(rs.getString("Last_name"));
        v2.setText(rs.getString("VILLAGE"));
        t2.setText(rs.getString("TALUKA"));
        d2.setText(rs.getString("District"));  
        s2.setText(rs.getString("State"));
        inc1.setText(rs.getString("Income_annum"));
        int inco = Integer.parseInt(inc1.getText());
        if(inco<300000)
        {
            inc2.setText("Below Poverty Line");
        }
        else if(inco>=300000 && inco<600000)
        {
            inc2.setText("Low Income Group");
        }
        else if(inco>=600000 && inco<1200000)
        {
            inc2.setText("Medium Income Group");
        }
        else
        {
            inc2.setText("High Income Group");
        }
        gen1.setText(rs.getString("Gender"));        
        ms2.setText(rs.getString("Marital_status"));
         Date date = rs.getDate("DOB");
         if(!(date.toString().matches("")))
         {
             dob1.setText(date.toString());
        DateFormat oDateFormat = new SimpleDateFormat("dd-MM-yy");
        String szDate = oDateFormat.format(date);
        LocalDate ld = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        System.out.println(szDate);
        Period p = Period.between( ld , LocalDate.now());
        String aged = Integer.toString(p.getYears());
        System.out.println("Age " + aged);
        System.out.println(p.getYears());
        age1.setText(aged);     
         }
    }
    } catch (SQLException e ) {
    JOptionPane.showMessageDialog(null, e); 

    }    
           
// TODO add your handling code here:
    }//GEN-LAST:event_view_mainActionPerformed
    
    
    private void view_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_subActionPerformed
         doc1.setVisible(false);
    app_home.setVisible(false);
        view.setVisible(false);
        view1.setVisible(true);   
        try {
        conn c = new conn();
        con=c.getconn();
        st = con.createStatement();
        String sql = "SELECT  First_name,Middle_name,Last_name,VILLAGE,TALUKA,DISTRICT,STATE,Income_annum,Gender,Marital_status,DOB,Aadhar_no FROM APPLICANTS WHERE Applicant_no = '"+app_no1.getText()+"'";
        rs = st.executeQuery(sql);
    while(rs.next())
    {     
         a_no1.setText(rs.getString("Aadhar_no"));
        f_name2.setText(rs.getString("First_name"));
        m_name2.setText(rs.getString("Middle_name"));
        l_name2.setText(rs.getString("Last_name"));
        v2.setText(rs.getString("VILLAGE"));
        t2.setText(rs.getString("TALUKA"));
        d2.setText(rs.getString("District"));  
        s2.setText(rs.getString("State"));
        inc1.setText(rs.getString("Income_annum"));
        gen1.setText(rs.getString("Gender"));        
        ms2.setText(rs.getString("Marital_status"));
         Date date = rs.getDate("DOB");
         dob1.setText(date.toString());  
        DateFormat oDateFormat = new SimpleDateFormat("dd-MM-yy");
        String szDate = oDateFormat.format(date);
        LocalDate ld = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        System.out.println(szDate);
        Period p = Period.between( ld , LocalDate.now());
        String aged = Integer.toString(p.getYears());
        System.out.println("Age " + aged);
        System.out.println(p.getYears());
        age1.setText(aged);     
         int inco = Integer.parseInt(inc1.getText());
        if(inco<300000)
        {
            inc2.setText("Below Poverty Line");
        }
        else if(inco>=300000 && inco<600000)
        {
            inc2.setText("Low Income Group");
        }
        else if(inco>=600000 && inco<1200000)
        {
            inc2.setText("Medium Income Group");
        }
        else
        {
            inc2.setText("High Income Group");
        }
    }
    } catch (SQLException e ) {
    JOptionPane.showMessageDialog(null, e); 

    }    
         
        // TODO add your handling code here:
    }//GEN-LAST:event_view_subActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
          conn c = new conn();
        con=c.getconn();

        String valid="true";
        String mc_pass=null,rc_pass=null,ac_pass=null,bc_pass=null,ic_pass=null,dc_pass=null,user_no = app_no.getText();
       
        String q1 = "select aadhar_copy,birth_cert_copy,income_cert_copy,ration_copy,marriage_copy,death_copy from APPL_DOCS_SUBMIT where appl_num='"+app_no.getText()+"'";
        try
        {
                st = con.createStatement();
                rs = st.executeQuery(q1);
              
                while(rs.next()) 
                { 
                    ac_pass = (rs.getString("aadhar_copy"));
                    bc_pass = (rs.getString("birth_cert_copy"));
                    ic_pass = (rs.getString("income_cert_copy")); 
                    rc_pass = (rs.getString("ration_copy"));
                    mc_pass = (rs.getString("marriage_copy"));
                    dc_pass = (rs.getString("death_copy"));  
                    System.out.println(ac_pass+"\n"+bc_pass+"\n"+ic_pass+"\n"+rc_pass+"\n"+mc_pass+"\n"+dc_pass+"\n");
    
                    if(ac_pass.equalsIgnoreCase("YES"))
                    {
                       acy2.setSelected(true);
                       System.out.print("acy2");
                    }
                    else
                    {
                       acn2.setSelected(true);
                       System.out.print("acn2");
                    }
                    if(bc_pass.equalsIgnoreCase("YES"))
                    {
                        bcy2.setSelected(true);
                                   System.out.print("bcy2");
                    }
                    else
                    {
                       bcn2.setSelected(true);
                                  System.out.print("bcn2");
                    }
                    if(ic_pass.equalsIgnoreCase("YES"))
                    {
                        icy2.setSelected(true);
                    }
                    else
                    {
                       icn2.setSelected(true);
                    }
                    if(rc_pass.equalsIgnoreCase("YES"))
                    {
                        rcy2.setSelected(true);
                    }
                    else
                    {
                       rcn2.setSelected(true);
                    }
                    if(mc_pass .equalsIgnoreCase("YES"))
                    {
                        mcn2.setSelected(true);
                    }
                    else if(mc_pass.equalsIgnoreCase("NO"))
                    {
                       mcn2.setSelected(true);
                    }
                    else
                    {
                        mcn2.setEnabled(false);
                        mcy2.setEnabled(false); 
                    }
                    if(dc_pass.equalsIgnoreCase("YES"))
                    {
                        dcy2.setSelected(true);
                    }
                    else if(dc_pass.equalsIgnoreCase("NO"))
                    {
                       dcn2.setSelected(true);
                    }
                    else
                    {
                        dcn2.setEnabled(false);
                        dcy2.setEnabled(false);   
                    }
                }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        String q2 = "insert into APPL_DOCS_SUBMIT(aadhar_copy,birth_cert_copy,income_cert_copy,ration_copy,marriage_copy,death_copy,appl_num)  values(?,?,?,?,?,?,?)";
        try
        {
            pst = con.prepareStatement(q2);

            pst.setObject(1,ac_pass);
            pst.setString(2,bc_pass);
            pst.setString(3,ic_pass);
            pst.setString(4,rc_pass);
            pst.setString(5, mc_pass);
            pst.setString(6, dc_pass);
            pst.setString(7,user_no);

            pst.execute();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e); 
        }
       

    }//GEN-LAST:event_submit2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicant_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicant_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicant_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicant_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applicant_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_no1;
    private javax.swing.ButtonGroup ac;
    private javax.swing.JRadioButton acn2;
    private javax.swing.JRadioButton acy2;
    private javax.swing.JButton add_det;
    private javax.swing.JTextField age1;
    private javax.swing.JPanel app_home;
    private javax.swing.JLabel app_no;
    private javax.swing.JLabel app_no1;
    private javax.swing.JLabel app_no2;
    private javax.swing.JLabel app_no3;
    private javax.swing.ButtonGroup bc;
    private javax.swing.JRadioButton bcn2;
    private javax.swing.JRadioButton bcy2;
    private javax.swing.JTextField c_no;
    private javax.swing.JTextField d2;
    private javax.swing.ButtonGroup dc;
    private javax.swing.JRadioButton dcn2;
    private javax.swing.JRadioButton dcy2;
    private javax.swing.JTextField dob1;
    private javax.swing.JPanel doc1;
    private javax.swing.JTextField f_name2;
    private javax.swing.ButtonGroup g;
    private javax.swing.JTextField gen1;
    private javax.swing.JButton home;
    private javax.swing.ButtonGroup ic;
    private javax.swing.JRadioButton icn2;
    private javax.swing.JRadioButton icy2;
    private javax.swing.JTextField inc1;
    private javax.swing.JTextField inc2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField l_name2;
    private javax.swing.JButton log_out;
    private javax.swing.JTextField m_name2;
    private javax.swing.ButtonGroup mc;
    private javax.swing.JRadioButton mcn2;
    private javax.swing.JRadioButton mcy2;
    private javax.swing.ButtonGroup ms;
    private javax.swing.JTextField ms2;
    private javax.swing.ButtonGroup rc;
    private javax.swing.JRadioButton rcn2;
    private javax.swing.JRadioButton rcy2;
    private javax.swing.JTextField s2;
    private javax.swing.JButton submit2;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField v2;
    private javax.swing.JPanel view;
    private javax.swing.JPanel view1;
    private javax.swing.JButton view_det;
    private javax.swing.JButton view_main;
    private javax.swing.JButton view_sub;
    // End of variables declaration//GEN-END:variables
}
