/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rural_housing;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhik
 */
public class company_main extends javax.swing.JFrame {
Connection con = null;
    ResultSet rs = null;
     ResultSet rs1 = null;
    PreparedStatement pst = null;
     PreparedStatement pst1 = null;
    Statement st=null;
    Statement st1=null;
    /**
     * Creates new form company_main
     */
    public company_main() {
        initComponents();
         view_ten.setVisible(false);
        v_detail.setVisible(false);
        sub_tender.setVisible(false);
        com_main.setVisible(false);
        com_main.setVisible(true);
         submit2.setVisible(false);
        viewproj.setVisible(false);

        jLabel9.setVisible(false);
        gst_no.setVisible(false);
    }
    
    public company_main(String abc) {
        initComponents();
         view_ten.setVisible(false);
        v_detail.setVisible(false);
        sub_tender.setVisible(false);
        com_main.setVisible(false);
        com_main.setVisible(true);
         submit2.setVisible(false);
        viewproj.setVisible(false);
        com_no.setText(abc);
        jLabel9.setVisible(false);
        gst_no.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        view_det = new javax.swing.JButton();
        home = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        sub_ten = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        view_det1 = new javax.swing.JButton();
        com_main = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        com_no = new javax.swing.JLabel();
        v_detail = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gst_no = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comp_name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cn2 = new javax.swing.JTextField();
        submit1 = new javax.swing.JButton();
        cn1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        comp_name1 = new javax.swing.JTextField();
        sub_tender = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        s = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        d = new javax.swing.JComboBox<>();
        t = new javax.swing.JComboBox<>();
        v = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        viewproj = new javax.swing.JScrollPane();
        view_proj = new javax.swing.JTable();
        submit2 = new javax.swing.JButton();
        view_ten = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        submit4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        see_tender = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 960));
        setMinimumSize(new java.awt.Dimension(1200, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rural_housing/Logo.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(330, 330, 330))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 180));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 580));

        view_det.setBackground(new java.awt.Color(0, 204, 204));
        view_det.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        view_det.setMnemonic('V');
        view_det.setText("View Company Details");
        view_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_detActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 204, 204));
        home.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        home.setMnemonic('H');
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        log_out.setBackground(new java.awt.Color(0, 204, 204));
        log_out.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        log_out.setMnemonic('L');
        log_out.setText("Log Out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        sub_ten.setBackground(new java.awt.Color(0, 204, 204));
        sub_ten.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        sub_ten.setMnemonic('T');
        sub_ten.setText("Submit Tender");
        sub_ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_tenActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setText("Company Login");

        view_det1.setBackground(new java.awt.Color(0, 204, 204));
        view_det1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        view_det1.setMnemonic('A');
        view_det1.setText("View Available Tenders");
        view_det1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_det1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel17)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_det, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(log_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82))
                    .addComponent(sub_ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(view_det1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(view_det)
                .addGap(39, 39, 39)
                .addComponent(view_det1)
                .addGap(38, 38, 38)
                .addComponent(sub_ten)
                .addGap(104, 104, 104)
                .addComponent(home)
                .addGap(50, 50, 50)
                .addComponent(log_out)
                .addGap(83, 83, 83))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, -1));

        com_main.setBackground(new java.awt.Color(0, 153, 153));
        com_main.setMaximumSize(new java.awt.Dimension(870, 780));
        com_main.setMinimumSize(new java.awt.Dimension(870, 580));
        com_main.setPreferredSize(new java.awt.Dimension(870, 580));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 29)); // NOI18N
        jLabel2.setText("Welcome To Rural Housing Allocation System.");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setText("Company Login");

        com_no.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        com_no.setText("Label");

        javax.swing.GroupLayout com_mainLayout = new javax.swing.GroupLayout(com_main);
        com_main.setLayout(com_mainLayout);
        com_mainLayout.setHorizontalGroup(
            com_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(com_mainLayout.createSequentialGroup()
                .addGroup(com_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(com_mainLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2))
                    .addGroup(com_mainLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel16)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, com_mainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(com_no)
                .addGap(395, 395, 395))
        );
        com_mainLayout.setVerticalGroup(
            com_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(com_mainLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(com_no, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        getContentPane().add(com_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, -1));

        v_detail.setBackground(new java.awt.Color(0, 153, 153));
        v_detail.setMaximumSize(new java.awt.Dimension(870, 780));
        v_detail.setMinimumSize(new java.awt.Dimension(870, 580));
        v_detail.setName(""); // NOI18N
        v_detail.setPreferredSize(new java.awt.Dimension(880, 580));
        v_detail.setRequestFocusEnabled(false);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel8.setText("Development Company Details");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel9.setText("Company GST Number:");

        gst_no.setEditable(false);
        gst_no.setBackground(new java.awt.Color(0, 204, 204));
        gst_no.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        gst_no.setText("Enter the company's 15 digit GST number");
        gst_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gst_noActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setText("Company Name:");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel11.setText("Company Status:");

        comp_name.setEditable(false);
        comp_name.setBackground(new java.awt.Color(0, 204, 204));
        comp_name.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        comp_name.setText("Enter the company name");
        comp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_nameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setText("Contact Number:");

        cn2.setEditable(false);
        cn2.setBackground(new java.awt.Color(0, 204, 204));
        cn2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cn2.setText("10 Digit Contact Number (optional)");
        cn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cn2ActionPerformed(evt);
            }
        });

        submit1.setBackground(new java.awt.Color(0, 153, 153));
        submit1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit1.setMnemonic('b');
        submit1.setText("Back");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        cn1.setEditable(false);
        cn1.setBackground(new java.awt.Color(0, 204, 204));
        cn1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cn1.setText("10 Digit Contact Number");
        cn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cn1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel13.setText("Experience");

        comp_name1.setEditable(false);
        comp_name1.setBackground(new java.awt.Color(0, 204, 204));
        comp_name1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        comp_name1.setText("Enter the company name");
        comp_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_name1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout v_detailLayout = new javax.swing.GroupLayout(v_detail);
        v_detail.setLayout(v_detailLayout);
        v_detailLayout.setHorizontalGroup(
            v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_detailLayout.createSequentialGroup()
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(v_detailLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_detailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)))
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gst_no, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                        .addComponent(comp_name)
                        .addComponent(cn1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(cn2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comp_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_detailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_detailLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_detailLayout.createSequentialGroup()
                        .addComponent(submit1)
                        .addGap(362, 362, 362))))
        );
        v_detailLayout.setVerticalGroup(
            v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comp_name, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comp_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(gst_no, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(31, 31, 31)
                .addComponent(submit1)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        getContentPane().add(v_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, -1));

        sub_tender.setBackground(new java.awt.Color(0, 153, 153));
        sub_tender.setMaximumSize(new java.awt.Dimension(870, 780));
        sub_tender.setMinimumSize(new java.awt.Dimension(870, 580));
        sub_tender.setPreferredSize(new java.awt.Dimension(870, 580));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("Project State:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setText("Project Village:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setText("Project District:");

        submit.setBackground(new java.awt.Color(0, 153, 153));
        submit.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit.setMnemonic('S');
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        s.setBackground(new java.awt.Color(0, 204, 204));
        s.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select State-", "Chhattisgarh", "Maharashtra", "Madhya Pradesh", "West Bengal" }));
        s.setToolTipText("");
        s.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setText("Project Taluka:");

        d.setBackground(new java.awt.Color(0, 204, 204));
        d.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select District-" }));
        d.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dItemStateChanged(evt);
            }
        });
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dMouseClicked(evt);
            }
        });

        t.setBackground(new java.awt.Color(0, 204, 204));
        t.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        t.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Taluka-" }));
        t.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tItemStateChanged(evt);
            }
        });
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });

        v.setBackground(new java.awt.Color(0, 204, 204));
        v.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        v.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Village-" }));
        v.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vMouseClicked(evt);
            }
        });
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setText("Submit Project Tender");

        view_proj.setBackground(new java.awt.Color(0, 153, 153));
        view_proj.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        view_proj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Click", "Site Code", "GDP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        view_proj.getTableHeader().setReorderingAllowed(false);
        viewproj.setViewportView(view_proj);
        if (view_proj.getColumnModel().getColumnCount() > 0) {
            view_proj.getColumnModel().getColumn(0).setResizable(false);
            view_proj.getColumnModel().getColumn(1).setResizable(false);
            view_proj.getColumnModel().getColumn(2).setResizable(false);
        }

        submit2.setBackground(new java.awt.Color(0, 153, 153));
        submit2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit2.setMnemonic('S');
        submit2.setText("SUBMIT");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sub_tenderLayout = new javax.swing.GroupLayout(sub_tender);
        sub_tender.setLayout(sub_tenderLayout);
        sub_tenderLayout.setHorizontalGroup(
            sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sub_tenderLayout.createSequentialGroup()
                .addGroup(sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sub_tenderLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(submit))
                    .addGroup(sub_tenderLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGroup(sub_tenderLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5)))
                        .addGap(96, 96, 96)
                        .addGroup(sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sub_tenderLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel3))
                    .addGroup(sub_tenderLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(submit2))
                    .addGroup(sub_tenderLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(viewproj, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        sub_tenderLayout.setVerticalGroup(
            sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sub_tenderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sub_tenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addGap(64, 64, 64)
                .addComponent(viewproj, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(submit2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(sub_tender, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 860, -1));

        view_ten.setBackground(new java.awt.Color(0, 153, 153));
        view_ten.setMaximumSize(new java.awt.Dimension(870, 780));
        view_ten.setMinimumSize(new java.awt.Dimension(870, 580));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel20.setText("View Available Tender");

        submit4.setBackground(new java.awt.Color(0, 153, 153));
        submit4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit4.setMnemonic('S');
        submit4.setText("SUBMIT");
        submit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit4ActionPerformed(evt);
            }
        });

        see_tender.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Project id", "State", "District", "Taluka", "Village", "Min Budget", "Start date", "End Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(see_tender);
        if (see_tender.getColumnModel().getColumnCount() > 0) {
            see_tender.getColumnModel().getColumn(0).setResizable(false);
            see_tender.getColumnModel().getColumn(1).setResizable(false);
            see_tender.getColumnModel().getColumn(2).setResizable(false);
            see_tender.getColumnModel().getColumn(3).setResizable(false);
            see_tender.getColumnModel().getColumn(4).setResizable(false);
            see_tender.getColumnModel().getColumn(5).setResizable(false);
            see_tender.getColumnModel().getColumn(6).setResizable(false);
            see_tender.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout view_tenLayout = new javax.swing.GroupLayout(view_ten);
        view_ten.setLayout(view_tenLayout);
        view_tenLayout.setHorizontalGroup(
            view_tenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_tenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(218, 218, 218))
            .addGroup(view_tenLayout.createSequentialGroup()
                .addGroup(view_tenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_tenLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(submit4))
                    .addGroup(view_tenLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        view_tenLayout.setVerticalGroup(
            view_tenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_tenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(submit4)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(view_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_detActionPerformed
        v_detail.setVisible(false);
         view_ten.setVisible(false);
        sub_tender.setVisible(false);
        com_main.setVisible(false);
        v_detail.setVisible(true);
        try {
        conn c = new conn();
        con=c.getconn();
        st = con.createStatement();
        String sql = "SELECT  Status,Name,Contact_no,Experience FROM COMPANY WHERE Company_ID = '"+com_no.getText()+"'";
        rs = st.executeQuery(sql);
    while(rs.next())
    {     
        comp_name1.setText(rs.getString("Status"));
        comp_name.setText(rs.getString("Name"));
        cn1.setText(rs.getString("Contact_no"));
        cn2.setText(rs.getString("Experience"));
    }
    } catch (SQLException e ) {
    JOptionPane.showMessageDialog(null, e); 

    }    

        // TODO add your handling code here:
    }//GEN-LAST:event_view_detActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        v_detail.setVisible(false);
         view_ten.setVisible(false);
        sub_tender.setVisible(false);
        com_main.setVisible(false);
        com_main.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        this.setVisible(false);
        login re = new login();
        re.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_log_outActionPerformed

    private void sub_tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_tenActionPerformed
        v_detail.setVisible(false);
        sub_tender.setVisible(false);
         view_ten.setVisible(false);
        com_main.setVisible(false);  
        sub_tender.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_sub_tenActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        submit2.setVisible(true);
        viewproj.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) view_proj.getModel();
        model.setRowCount(0);
        conn c = new conn();
        con=c.getconn();
//        String state = s.getSelectedItem().toString();
  //      String dist = d.getSelectedItem().toString();
    //    String talu = t.getSelectedItem().toString();
        String vill = v.getSelectedItem().toString();
        String sql = "SELECT SITE_CODE , REGION_GDP from PROJECT WHERE VILLAGE = '"+vill+"';";
        try{
                st=con.createStatement();
                rs = st.executeQuery(sql);
                if (rs.next())
                {
                    String code = rs.getString("SITE_CODE");
                    Float sf_name = rs.getFloat("REGION_GDP");
                    Object[] o =  { null , code, sf_name };
                  
                    model.addRow(o);
                    
                }
        }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_submitActionPerformed

    private void sItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sItemStateChanged
        /*if(s.getSelectedItem().toString().equalsIgnoreCase("Maharashtra"))
        {
            d.removeAllItems();
            d.addItem("Buldhana");
            d.addItem("Nashik");
            d.addItem("Dhule");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("Chhattisgarh"))
        {
            d.removeAllItems();
            d.addItem("Bilaspur");
            d.addItem("Korba");
            d.addItem("Raipur");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("West Bengal"))
        {
            d.removeAllItems();
            d.addItem("Hoogly");
            d.addItem("Birbhum");
            d.addItem("South 24 Parganas");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("Madhya pradesh"))
        {
            d.removeAllItems();
            d.addItem("Dhar");
            d.addItem("Guna");
            d.addItem("Panna");
        } */ 
        // TODO add your handling code here:
    }//GEN-LAST:event_sItemStateChanged

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vActionPerformed

    private void gst_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gst_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gst_noActionPerformed

    private void comp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comp_nameActionPerformed

    private void cn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cn2ActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        v_detail.setVisible(false);
        sub_tender.setVisible(false);
        com_main.setVisible(false);
         view_ten.setVisible(false);
        com_main.setVisible(true);

    }//GEN-LAST:event_submit1ActionPerformed

    private void cn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cn1ActionPerformed

    private void dItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dItemStateChanged
       /*if(d.getSelectedItem().toString().equalsIgnoreCase("Buldhana"))
        {
            t.removeAllItems();
            t.addItem("Deulgaon Raja");
            t.addItem("Lonar");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            t.removeAllItems();
            t.addItem("Nashik");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Dhule"))
        {
            t.removeAllItems();
            t.addItem("Shirpur");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Bilaspur"))
        {
            t.removeAllItems();
            t.addItem("Marwani");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Korba"))
        {
            t.removeAllItems();
            t.addItem("Pali");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Raipur"))
        {
            t.removeAllItems();
            t.addItem("Arang");
            t.addItem("Tilda");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Hoogly"))
        {
            t.removeAllItems();
            t.addItem("Haripal");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Birbhum"))
        {
            t.removeAllItems();
            t.addItem("Nanoor");
            t.addItem("Labpur");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("South 24 Paraganas"))
        {
            t.removeAllItems();
            t.addItem("Kulpi");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Dhar"))
        {
            t.removeAllItems();
            t.addItem("Bagh");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Guna"))
        {
            t.removeAllItems();
            t.addItem("Aron");
            t.addItem("Chanchoda");
            t.addItem("Bamori");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Panna"))
        {
            t.removeAllItems();
            t.addItem("Gunor");
        }*/ // TODO add your handling code here:
    }//GEN-LAST:event_dItemStateChanged

    private void tItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tItemStateChanged
/*if(t.getSelectedItem().toString().equalsIgnoreCase("Deulgaon Raja"))
        {
            v.removeAllItems();
            v.addItem("Aaland");
            v.addItem("Umbarkhed");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Lonar"))
        {
            v.removeAllItems();
            v.addItem("Hirdav");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            v.removeAllItems();
            v.addItem("Matori");
            v.addItem("Dari");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Shirpur"))
        {
            v.removeAllItems();
            v.addItem("Jalod");
            v.addItem("Mandal");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Marwahi"))
        {
            v.removeAllItems();
            v.addItem("Dhanpur");
            v.addItem("Lohari");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Pali"))
        {
            v.removeAllItems();
            v.addItem("Batra");
            v.addItem("Sirli");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Arang"))
        {
            v.removeAllItems();
            v.addItem("Ameri");
            v.addItem("Nisda");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Haripal"))
        {
            v.removeAllItems();
            v.addItem("Kaikala");
            v.addItem("Jejur");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Nanoor"))
        {
            v.removeAllItems();
            v.addItem("Thupsara");
            v.addItem("Jalundi");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Kulpi"))
        {
            v.removeAllItems();
            v.addItem("Dhola");
            v.addItem("Ramkishore");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Bagh"))
        {
            v.removeAllItems();
            v.addItem("Devdha");
            v.addItem("Jali");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Aron"))
        {
            v.removeAllItems();
            v.addItem("Davri");
            v.addItem("Patan");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Gunor"))
        {
            v.removeAllItems();
            v.addItem("Ganj");
            v.addItem("Kamtana");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Tilda"))
        {
            v.removeAllItems();
            v.addItem("Bhiloni");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Labpur"))
        {
            v.removeAllItems();
            v.addItem("Jamna");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Chanchoda"))
        {
            v.removeAllItems();
            v.addItem("Murela");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Bamori"))
        {
            v.removeAllItems();
            v.addItem("Rampur");
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_tItemStateChanged

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
        conn c = new conn();
        con=c.getconn();
        int status=0,work=0;
        String arrange=null;
        String ne = "Select count(*) as no from PROJECT where COMPANY_CODE='"+com_no.getText().toString()+"'";
        try
        {
            pst1 = con.prepareStatement(ne);
            rs = pst1.executeQuery();
            while(rs.next())
            {
                work=rs.getInt("no");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        String stat = "Select status from COMPANY where Company_ID='"+com_no.getText().toString()+"'";
        try
        {
            pst1 = con.prepareStatement(stat);
            rs = pst1.executeQuery();
            while(rs.next())
            {
                arrange=rs.getString("status");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                    
        if(arrange.equalsIgnoreCase("national"))
        {
            status=5;
        }
        else if(arrange.equalsIgnoreCase("state"))
        {
            status=3;
        }
        
        Boolean chked = Boolean.valueOf(view_proj.getValueAt(0, 0).toString());
        String dataCol1 = view_proj.getValueAt(0, 1).toString();
        
        if (chked)
        {
            if(work<status)
            {
                try
        {
            String a  = com_no.getText();
            String chk = "SELECT * FROM TENDER WHERE com = '"+a+"' AND project = '"+dataCol1+"'";
            pst1 = con.prepareStatement(chk);
            ResultSet ab = pst1.executeQuery();
            int count = 0;
            while(ab.next())
            {
                count++;
            }
            if(count == 0)
            {
              String sql = "INSERT INTO TENDER VALUES ('MOH001','"+a+"','"+dataCol1+"')";
                try{
                        pst=con.prepareStatement(sql);
                        Boolean b = pst.execute();

                        if(!b)
                        {
                            JOptionPane.showMessageDialog(null, "Tender submitted ");            
                            System.out.println("success");
                            v_detail.setVisible(false);
                            sub_tender.setVisible(false);
                            com_main.setVisible(false);
                            submit2.setVisible(false);
                            viewproj.setVisible(false);
                            com_main.setVisible(true);

                        }
                        else
                        {
                            System.out.println("stuck somewhere");

                        }
                    }
                    catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Tender already submitted for this Project"); 
                    v_detail.setVisible(false);
                    sub_tender.setVisible(false);
                    com_main.setVisible(false);
                    submit2.setVisible(false);
                    viewproj.setVisible(false);
                    com_main.setVisible(true);          
                }
            }// TODO add your handling code here:

            catch (SQLException ex)
            {
                Logger.getLogger(company_main.class.getName()).log(Level.SEVERE,null, ex);
            } 
        }
           else
            {
                    JOptionPane.showMessageDialog(null, "Maximum no of tender submitted or project alloted as per status"); 
                    v_detail.setVisible(false);
                    sub_tender.setVisible(false);
                    com_main.setVisible(false);
                    submit2.setVisible(false);
                    viewproj.setVisible(false);
                    com_main.setVisible(true);          
                
            }
        }
    }//GEN-LAST:event_submit2ActionPerformed

    private void dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseClicked
       if(s.getSelectedItem().toString().equalsIgnoreCase("Maharashtra"))
        {
            d.removeAllItems();
            d.addItem("Buldhana");
            d.addItem("Nashik");
            d.addItem("Dhule");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("Chhattisgarh"))
        {
            d.removeAllItems();
            d.addItem("Bilaspur");
            d.addItem("Korba");
            d.addItem("Raipur");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("West Bengal"))
        {
            d.removeAllItems();
            d.addItem("Hoogly");
            d.addItem("Birbhum");
            d.addItem("South 24 Parganas");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("Madhya pradesh"))
        {
            d.removeAllItems();
            d.addItem("Dhar");
            d.addItem("Guna");
            d.addItem("Panna");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_dMouseClicked

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
    if(d.getSelectedItem().toString().equalsIgnoreCase("Buldhana"))
        {
            t.removeAllItems();
            t.addItem("Deulgaon Raja");
            t.addItem("Lonar");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            t.removeAllItems();
            t.addItem("Nashik");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Dhule"))
        {
            t.removeAllItems();
            t.addItem("Shirpur");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Bilaspur"))
        {
            t.removeAllItems();
            t.addItem("Marwani");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Korba"))
        {
            t.removeAllItems();
            t.addItem("Pali");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Raipur"))
        {
            t.removeAllItems();
            t.addItem("Arang");
            t.addItem("Tilda");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Hoogly"))
        {
            t.removeAllItems();
            t.addItem("Haripal");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Birbhum"))
        {
            t.removeAllItems();
            t.addItem("Nanoor");
            t.addItem("Labpur");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("South 24 Paraganas"))
        {
            t.removeAllItems();
            t.addItem("Kulpi");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Dhar"))
        {
            t.removeAllItems();
            t.addItem("Bagh");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Guna"))
        {
            t.removeAllItems();
            t.addItem("Aron");
            t.addItem("Chanchoda");
            t.addItem("Bamori");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Panna"))
        {
            t.removeAllItems();
            t.addItem("Gunor");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_tMouseClicked

    private void vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseClicked
       if(t.getSelectedItem().toString().equalsIgnoreCase("Deulgaon Raja"))
        {
            v.removeAllItems();
            v.addItem("Aaland");
            v.addItem("Umbarkhed");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Lonar"))
        {
            v.removeAllItems();
            v.addItem("Hirdav");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            v.removeAllItems();
            v.addItem("Matori");
            v.addItem("Dari");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Shirpur"))
        {
            v.removeAllItems();
            v.addItem("Jalod");
            v.addItem("Mandal");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Marwahi"))
        {
            v.removeAllItems();
            v.addItem("Dhanpur");
            v.addItem("Lohari");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Pali"))
        {
            v.removeAllItems();
            v.addItem("Batra");
            v.addItem("Sirli");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Arang"))
        {
            v.removeAllItems();
            v.addItem("Ameri");
            v.addItem("Nisda");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Haripal"))
        {
            v.removeAllItems();
            v.addItem("Kaikala");
            v.addItem("Jejur");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Nanoor"))
        {
            v.removeAllItems();
            v.addItem("Thupsara");
            v.addItem("Jalundi");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Kulpi"))
        {
            v.removeAllItems();
            v.addItem("Dhola");
            v.addItem("Ramkishore");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Bagh"))
        {
            v.removeAllItems();
            v.addItem("Devdha");
            v.addItem("Jali");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Aron"))
        {
            v.removeAllItems();
            v.addItem("Davri");
            v.addItem("Patan");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Gunor"))
        {
            v.removeAllItems();
            v.addItem("Ganj");
            v.addItem("Kamtana");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Tilda"))
        {
            v.removeAllItems();
            v.addItem("Bhiloni");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Labpur"))
        {
            v.removeAllItems();
            v.addItem("Jamna");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Chanchoda"))
        {
            v.removeAllItems();
            v.addItem("Murela");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Bamori"))
        {
            v.removeAllItems();
            v.addItem("Rampur");
        } // TODO add your handling code here:
    }//GEN-LAST:event_vMouseClicked

    private void comp_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comp_name1ActionPerformed

    private void view_det1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_det1ActionPerformed
  v_detail.setVisible(false);
        sub_tender.setVisible(false);
        com_main.setVisible(false);
         submit2.setVisible(false);
        viewproj.setVisible(false);
             
        view_ten.setVisible(true);
        DefaultTableModel model1 = (DefaultTableModel) see_tender.getModel();
        model1.setRowCount(0);
        conn c = new conn();
        con=c.getconn();
        String sql = "SELECT SITE_CODE,Start_Date,End_date,quot from Tender_by_moh ";
        
        try{
            String t1=null,t2=null,t3=null,t4=null,t5=null,t6=null,t7=null,t8=null;
        
                st=con.createStatement();
                rs = st.executeQuery(sql);
                while(rs.next())
                {
                     t1 = rs.getString("SITE_CODE");
                     t2 = rs.getString("Start_Date");
                     t3 = rs.getString("End_Date");
                     t4 = rs.getString("quot");
                          String sql1 = "SELECT STATE,DISTRICT,TALUKA,VILLAGE from PROJECT where SITE_CODE = '"+t1+"'";
                    try{
                        st1=con.createStatement();
                        rs1 = st1.executeQuery(sql1);
                        if(rs1.next())
                        {
                         t5 = rs1.getString("STATE");
                         t6 = rs1.getString("DISTRICT");   
                         t7 = rs1.getString("TALUKA");
                         t8 = rs1.getString("VILLAGE");

                        }
                    }
                  catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    Object[] o =  { t1,t5,t6,t7,t8,t4,t2,t3};     
                    model1.addRow(o);                 
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_view_det1ActionPerformed

    private void submit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(company_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(company_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(company_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(company_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cn1;
    private javax.swing.JTextField cn2;
    private javax.swing.JPanel com_main;
    private javax.swing.JLabel com_no;
    private javax.swing.JTextField comp_name;
    private javax.swing.JTextField comp_name1;
    private javax.swing.JComboBox<String> d;
    private javax.swing.JTextField gst_no;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton log_out;
    private javax.swing.JComboBox<String> s;
    private javax.swing.JTable see_tender;
    private javax.swing.JButton sub_ten;
    private javax.swing.JPanel sub_tender;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JButton submit2;
    private javax.swing.JButton submit4;
    private javax.swing.JComboBox<String> t;
    private javax.swing.JComboBox<String> v;
    private javax.swing.JPanel v_detail;
    private javax.swing.JButton view_det;
    private javax.swing.JButton view_det1;
    private javax.swing.JTable view_proj;
    private javax.swing.JPanel view_ten;
    private javax.swing.JScrollPane viewproj;
    // End of variables declaration//GEN-END:variables
}
