/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rural_housing;

/**
 *
 * @author Abhik
 */
public class CSMC_main extends javax.swing.JFrame {

    /**
     * Creates new form CSMC_main
     */
    public CSMC_main() {
        initComponents();
        app_sua.setVisible(false);
        cpr.setVisible(false);
      csmc_home.setVisible(true);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        view_det = new javax.swing.JButton();
        home = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        prj_rep = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        prj_rep1 = new javax.swing.JButton();
        csmc_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        app_sua = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        submit2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        d = new javax.swing.JComboBox<>();
        t = new javax.swing.JComboBox<>();
        v = new javax.swing.JComboBox<>();
        s = new javax.swing.JComboBox<>();
        cpr = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rural_housing/Logo.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(330, 330, 330))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 180));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        view_det.setBackground(new java.awt.Color(0, 204, 204));
        view_det.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        view_det.setMnemonic('V');
        view_det.setText("View Agent Details");
        view_det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_detActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 204, 204));
        home.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        home.setMnemonic('H');
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        log_out.setBackground(new java.awt.Color(0, 204, 204));
        log_out.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        log_out.setMnemonic('L');
        log_out.setText("Log Out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        prj_rep.setBackground(new java.awt.Color(0, 204, 204));
        prj_rep.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        prj_rep.setMnemonic('P');
        prj_rep.setText("Create Project Report");
        prj_rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prj_repActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setText("CSMC Login");

        prj_rep1.setBackground(new java.awt.Color(0, 204, 204));
        prj_rep1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        prj_rep1.setMnemonic('A');
        prj_rep1.setText("Appoint Survey Agency");
        prj_rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prj_rep1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_det, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(log_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82))
                    .addComponent(prj_rep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(prj_rep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(view_det)
                .addGap(47, 47, 47)
                .addComponent(prj_rep)
                .addGap(53, 53, 53)
                .addComponent(prj_rep1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(home)
                .addGap(50, 50, 50)
                .addComponent(log_out)
                .addGap(83, 83, 83))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, 780));

        csmc_home.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 29)); // NOI18N
        jLabel2.setText("Welcome To Rural Housing Allocation System.");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setText("CSMC Login");

        javax.swing.GroupLayout csmc_homeLayout = new javax.swing.GroupLayout(csmc_home);
        csmc_home.setLayout(csmc_homeLayout);
        csmc_homeLayout.setHorizontalGroup(
            csmc_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csmc_homeLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(98, 98, 98))
            .addGroup(csmc_homeLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        csmc_homeLayout.setVerticalGroup(
            csmc_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csmc_homeLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(555, Short.MAX_VALUE))
        );

        getContentPane().add(csmc_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, 780));

        app_sua.setBackground(new java.awt.Color(0, 153, 153));
        app_sua.setMaximumSize(new java.awt.Dimension(880, 780));
        app_sua.setMinimumSize(new java.awt.Dimension(880, 780));
        app_sua.setPreferredSize(new java.awt.Dimension(880, 780));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel13.setText("Appoint Survey Agency");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setText("Project State:");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel15.setText("Project Village:");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel19.setText("Project District:");

        submit2.setBackground(new java.awt.Color(0, 153, 153));
        submit2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit2.setMnemonic('S');
        submit2.setText("SUBMIT");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel20.setText("Project Taluka:");

        d.setBackground(new java.awt.Color(0, 204, 204));
        d.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select District-" }));
        d.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dItemStateChanged(evt);
            }
        });

        t.setBackground(new java.awt.Color(0, 204, 204));
        t.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        t.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Taluka-" }));
        t.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tItemStateChanged(evt);
            }
        });

        v.setBackground(new java.awt.Color(0, 204, 204));
        v.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        v.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Village-" }));
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        s.setBackground(new java.awt.Color(0, 204, 204));
        s.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select State-", "Chhattisgarh", "Maharashtra", "Madhya Pradesh", "West Bengal" }));
        s.setToolTipText("");
        s.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout app_suaLayout = new javax.swing.GroupLayout(app_sua);
        app_sua.setLayout(app_suaLayout);
        app_suaLayout.setHorizontalGroup(
            app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_suaLayout.createSequentialGroup()
                .addGroup(app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(app_suaLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(app_suaLayout.createSequentialGroup()
                                .addGroup(app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(app_suaLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(app_suaLayout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(submit2))))
                    .addGroup(app_suaLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel13)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        app_suaLayout.setVerticalGroup(
            app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_suaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(15, 15, 15)
                .addGroup(app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(app_suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(app_suaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(28, 28, 28)
                        .addComponent(submit2))
                    .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(441, Short.MAX_VALUE))
        );

        getContentPane().add(app_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, 780));

        cpr.setBackground(new java.awt.Color(0, 153, 153));
        cpr.setMaximumSize(new java.awt.Dimension(880, 780));
        cpr.setMinimumSize(new java.awt.Dimension(880, 780));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setText("Detailed Project Report");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setText("Phase 4 - Completion of the rooms. Ready for possession.");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel5.setText("Phase 1 - Completion of Foundation.");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setText("Phase 2 - Completion of half of the proposed floors.");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel7.setText("Phase 3 - Completion of the complete structure.");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setText("Phase");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setText("Status");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel9.setText("Phase 1 Completed:");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel11.setText("Phase 3 Completed:");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel12.setText("Phase 4 Completed:");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel18.setText("Phase 2 Completed:");

        jRadioButton1.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton3.setText("No");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton4.setText("No");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton5.setText("No");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton6.setText("Yes");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton7.setText("Yes");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton8.setText("Yes");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel21.setText("Remarks (if any):");

        jTextArea1.setBackground(new java.awt.Color(0, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Remarks for the Phase completed");
        jScrollPane1.setViewportView(jTextArea1);

        jButton7.setBackground(new java.awt.Color(0, 153, 153));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton7.setText("SUBMIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cprLayout = new javax.swing.GroupLayout(cpr);
        cpr.setLayout(cprLayout);
        cprLayout.setHorizontalGroup(
            cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cprLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createSequentialGroup()
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel18)
                            .addGroup(cprLayout.createSequentialGroup()
                                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cprLayout.createSequentialGroup()
                                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(105, 105, 105))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(101, 101, 101)))
                                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(cprLayout.createSequentialGroup()
                                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton6)
                                            .addComponent(jRadioButton8)
                                            .addComponent(jRadioButton7))
                                        .addGap(64, 64, 64)
                                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton4)
                                            .addComponent(jRadioButton5)))
                                    .addComponent(jScrollPane1)))
                            .addComponent(jLabel12))
                        .addGap(95, 95, 95))))
            .addGroup(cprLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jButton7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        cprLayout.setVerticalGroup(
            cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cprLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cprLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cprLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(cprLayout.createSequentialGroup()
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(87, 87, 87))
        );

        getContentPane().add(cpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view_detActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_detActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_detActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
           
        app_sua.setVisible(false);
        cpr.setVisible(false);
      csmc_home.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
   this.setVisible(false);
       login re = new login();
       re.setVisible(true);         
// TODO add your handling code here:
    }//GEN-LAST:event_log_outActionPerformed

    private void prj_repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prj_repActionPerformed
        app_sua.setVisible(false);
        cpr.setVisible(true);
      csmc_home.setVisible(false);
     
// TODO add your handling code here:
    }//GEN-LAST:event_prj_repActionPerformed

    private void prj_rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prj_rep1ActionPerformed
        csmc_home.setVisible(false);
        app_sua.setVisible(true);
        cpr.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_prj_rep1ActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vActionPerformed

    private void sItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sItemStateChanged
              if(s.getSelectedItem().toString().equalsIgnoreCase("Maharashtra"))
        {
            d.removeAllItems();
            d.addItem("Buldhana");
            d.addItem("Nashik");
            d.addItem("Dhule");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("Chhattisgarh"))
        {
            d.removeAllItems();
            d.addItem("Bilaspur");
            d.addItem("Korba");
            d.addItem("Raipur");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("West Bengal"))
        {
            d.removeAllItems();
            d.addItem("Hoogly");
            d.addItem("Birbhum");
            d.addItem("South 24 Parganas");
        }
        else if(s.getSelectedItem().toString().equalsIgnoreCase("Madhya pradesh"))
        {
            d.removeAllItems();
            d.addItem("Dhar");
            d.addItem("Guna");
            d.addItem("Panna");
        }        // TODO add your handling code here:  // TODO add your handling code here:
    }//GEN-LAST:event_sItemStateChanged

    private void dItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dItemStateChanged
      if(d.getSelectedItem().toString().equalsIgnoreCase("Buldhana"))
        {
            t.removeAllItems();
            t.addItem("Deulgaon Raja");
            t.addItem("Lonar");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            t.removeAllItems();
            t.addItem("Nashik");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Dhule"))
        {
            t.removeAllItems();
            t.addItem("Shirpur");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Bilaspur"))
        {
            t.removeAllItems();
            t.addItem("Marwani");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Korba"))
        {
            t.removeAllItems();
            t.addItem("Pali");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Raipur"))
        {
            t.removeAllItems();
            t.addItem("Arang");
            t.addItem("Tilda");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Hoogly"))
        {
            t.removeAllItems();
            t.addItem("Haripal");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Birbhum"))
        {
            t.removeAllItems();
            t.addItem("Nanoor");
            t.addItem("Labpur");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("South 24 Paraganas"))
        {
            t.removeAllItems();
            t.addItem("Kulpi");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Dhar"))
        {
            t.removeAllItems();
            t.addItem("Bagh");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Guna"))
        {
            t.removeAllItems();
            t.addItem("Aron");
            t.addItem("Chanchoda");
            t.addItem("Bamori");
        }
        else if(d.getSelectedItem().toString().equalsIgnoreCase("Panna"))
        {
            t.removeAllItems();
            t.addItem("Gunor");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_dItemStateChanged

    private void tItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tItemStateChanged
        if(t.getSelectedItem().toString().equalsIgnoreCase("Deulgaon Raja"))
        {
            v.removeAllItems();
            v.addItem("Aaland");
            v.addItem("Umbarkhed");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Lonar"))
        {
            v.removeAllItems();
            v.addItem("Hirdav");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            v.removeAllItems();
            v.addItem("Matori");
            v.addItem("Dari");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Shirpur"))
        {
            v.removeAllItems();
            v.addItem("Jalod");
            v.addItem("Mandal");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Marwahi"))
        {
            v.removeAllItems();
            v.addItem("Dhanpur");
            v.addItem("Lohari");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Pali"))
        {
            v.removeAllItems();
            v.addItem("Batra");
            v.addItem("Sirli");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Arang"))
        {
            v.removeAllItems();
            v.addItem("Ameri");
            v.addItem("Nisda");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Haripal"))
        {
            v.removeAllItems();
            v.addItem("Kaikala");
            v.addItem("Jejur");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Nanoor"))
        {
            v.removeAllItems();
            v.addItem("Thupsara");
            v.addItem("Jalundi");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Kulpi"))
        {
            v.removeAllItems();
            v.addItem("Dhola");
            v.addItem("Ramkishore");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Bagh"))
        {
            v.removeAllItems();
            v.addItem("Devdha");
            v.addItem("Jali");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Aron"))
        {
            v.removeAllItems();
            v.addItem("Davri");
            v.addItem("Patan");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Gunor"))
        {
            v.removeAllItems();
            v.addItem("Ganj");
            v.addItem("Kamtana");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Tilda"))
        {
            v.removeAllItems();
            v.addItem("Bhiloni");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Labpur"))
        {
            v.removeAllItems();
            v.addItem("Jamna");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Chanchoda"))
        {
            v.removeAllItems();
            v.addItem("Murela");
        }
        else if(t.getSelectedItem().toString().equalsIgnoreCase("Bamori"))
        {
            v.removeAllItems();
            v.addItem("Rampur");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSMC_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSMC_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSMC_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSMC_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CSMC_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel app_sua;
    private javax.swing.JPanel cpr;
    private javax.swing.JPanel csmc_home;
    private javax.swing.JComboBox<String> d;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton log_out;
    private javax.swing.JButton prj_rep;
    private javax.swing.JButton prj_rep1;
    private javax.swing.JComboBox<String> s;
    private javax.swing.JButton submit2;
    private javax.swing.JComboBox<String> t;
    private javax.swing.JComboBox<String> v;
    private javax.swing.JButton view_det;
    // End of variables declaration//GEN-END:variables
}
