/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rural_housing;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Abhik
 */
public class CSMC_main1 extends javax.swing.JFrame {
Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement st = null;
    /**
     * Creates new form CSMC_main
     */
    public CSMC_main1() {
        initComponents();
       app_sua1.setVisible(false);
        sua.setVisible(false);
        cpr.setVisible(false);
      app_flats.setVisible(false);
      app_flats1.setVisible(false);
      csmc_home.setVisible(true);
      
    }
 public CSMC_main1(String aa) {
        initComponents();
       app_sua1.setVisible(false);
        sua.setVisible(false);
        cpr.setVisible(false);
      csmc_home.setVisible(true);
      csmc_no.setText(aa);
      app_flats1.setVisible(false);
      app_flats.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        csmc_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        csmc_no = new javax.swing.JLabel();
        cpr = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        info = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        p4 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        prj_rep = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        appt_sa = new javax.swing.JButton();
        appt_flats = new javax.swing.JButton();
        app_sua1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        submit5 = new javax.swing.JButton();
        p1 = new javax.swing.JComboBox<>();
        sua = new javax.swing.JPanel();
        dt = new javax.swing.JTextField();
        tt = new javax.swing.JTextField();
        vt = new javax.swing.JTextField();
        spsa = new javax.swing.JScrollPane();
        sa = new javax.swing.JTable();
        submit4 = new javax.swing.JButton();
        app_flats = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        submit3 = new javax.swing.JButton();
        p2 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        app_flats1 = new javax.swing.JPanel();
        dt1 = new javax.swing.JTextField();
        tt1 = new javax.swing.JTextField();
        vt1 = new javax.swing.JTextField();
        spsa1 = new javax.swing.JScrollPane();
        sa1 = new javax.swing.JTable();
        submit7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        flat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 960));
        setMinimumSize(new java.awt.Dimension(1200, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rural_housing/Logo.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(330, 330, 330))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 180));

        csmc_home.setBackground(new java.awt.Color(0, 153, 153));
        csmc_home.setMaximumSize(new java.awt.Dimension(871, 780));
        csmc_home.setMinimumSize(new java.awt.Dimension(871, 580));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 29)); // NOI18N
        jLabel2.setText("Welcome To Rural Housing Allocation System.");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setText("CSMC Login");

        csmc_no.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        csmc_no.setText("Label");

        javax.swing.GroupLayout csmc_homeLayout = new javax.swing.GroupLayout(csmc_home);
        csmc_home.setLayout(csmc_homeLayout);
        csmc_homeLayout.setHorizontalGroup(
            csmc_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csmc_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(98, 98, 98))
            .addGroup(csmc_homeLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addGroup(csmc_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(csmc_no))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        csmc_homeLayout.setVerticalGroup(
            csmc_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(csmc_homeLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(csmc_no, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        getContentPane().add(csmc_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, 580));

        cpr.setBackground(new java.awt.Color(0, 153, 153));
        cpr.setMaximumSize(new java.awt.Dimension(880, 780));
        cpr.setMinimumSize(new java.awt.Dimension(880, 580));
        cpr.setPreferredSize(new java.awt.Dimension(880, 580));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setText("Detailed Project Report");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setText("Phase");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setText("Status");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel9.setText("Phase 1 Completed:");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel11.setText("Phase 3 Completed:");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel12.setText("Phase 4 Completed:");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel18.setText("Phase 2 Completed:");

        jRadioButton1.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton1.setText("Yes");

        jRadioButton2.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton2.setText("No");

        jRadioButton3.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton3.setText("No");

        jRadioButton4.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton4.setText("No");

        jRadioButton5.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton5.setText("No");

        jRadioButton6.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton6.setText("Yes");

        jRadioButton7.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton7.setText("Yes");

        jRadioButton8.setBackground(new java.awt.Color(0, 153, 153));
        jRadioButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jRadioButton8.setText("Yes");

        jButton7.setBackground(new java.awt.Color(0, 153, 153));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton7.setText("SUBMIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel4.setText("Phase 4 - Completion of the rooms. Ready for possession.");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel5.setText("Phase 1 - Completion of Foundation.");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel6.setText("Phase 2 - Completion of half of the proposed floors.");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel7.setText("Phase 3 - Completion of the complete structure.");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
            .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        p4.setBackground(new java.awt.Color(0, 204, 204));
        p4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        p4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Project-" }));
        p4.setToolTipText("");

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel25.setText("Project :");

        jButton8.setBackground(new java.awt.Color(0, 153, 153));
        jButton8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton8.setText("SUBMIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cprLayout = new javax.swing.GroupLayout(cpr);
        cpr.setLayout(cprLayout);
        cprLayout.setHorizontalGroup(
            cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cprLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createSequentialGroup()
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cprLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(223, 223, 223))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cprLayout.createSequentialGroup()
                                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(p4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cprLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jButton8)))
                                .addGap(123, 123, 123)))
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(cprLayout.createSequentialGroup()
                                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel18))
                                .addGap(57, 57, 57)
                                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(cprLayout.createSequentialGroup()
                                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton6)
                                            .addComponent(jRadioButton8)
                                            .addComponent(jRadioButton7))
                                        .addGap(25, 25, 25)
                                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton4)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jRadioButton5)))))
                            .addComponent(jLabel12))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createSequentialGroup()
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(111, 111, 111))))
        );
        cprLayout.setVerticalGroup(
            cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cprLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createSequentialGroup()
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cprLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cprLayout.createSequentialGroup()
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton4)
                                .addComponent(jRadioButton8))
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cprLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(cprLayout.createSequentialGroup()
                                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton7)))))
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        getContentPane().add(cpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(330, 580));
        jPanel1.setMinimumSize(new java.awt.Dimension(330, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 550));

        home.setBackground(new java.awt.Color(0, 204, 204));
        home.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        home.setMnemonic('H');
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        log_out.setBackground(new java.awt.Color(0, 204, 204));
        log_out.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        log_out.setMnemonic('L');
        log_out.setText("Log Out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        prj_rep.setBackground(new java.awt.Color(0, 204, 204));
        prj_rep.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        prj_rep.setMnemonic('P');
        prj_rep.setText("Create Project Report");
        prj_rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prj_repActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setText("CSMC Login");

        appt_sa.setBackground(new java.awt.Color(0, 204, 204));
        appt_sa.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        appt_sa.setMnemonic('A');
        appt_sa.setText("Appoint Survey Agent");
        appt_sa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appt_saActionPerformed(evt);
            }
        });

        appt_flats.setBackground(new java.awt.Color(0, 204, 204));
        appt_flats.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        appt_flats.setMnemonic('A');
        appt_flats.setText("Allocate Flats");
        appt_flats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appt_flatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(log_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82))
                    .addComponent(prj_rep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(appt_sa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(appt_flats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(prj_rep)
                .addGap(21, 21, 21)
                .addComponent(appt_sa)
                .addGap(23, 23, 23)
                .addComponent(appt_flats)
                .addGap(75, 75, 75)
                .addComponent(home)
                .addGap(29, 29, 29)
                .addComponent(log_out)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 320, 580));

        app_sua1.setBackground(new java.awt.Color(0, 153, 153));
        app_sua1.setMaximumSize(new java.awt.Dimension(880, 780));
        app_sua1.setMinimumSize(new java.awt.Dimension(880, 550));
        app_sua1.setPreferredSize(new java.awt.Dimension(880, 580));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel15.setText("Appoint Survey Agent");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel20.setText("Project :");

        submit5.setBackground(new java.awt.Color(0, 153, 153));
        submit5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit5.setMnemonic('S');
        submit5.setText("SUBMIT");
        submit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit5ActionPerformed(evt);
            }
        });

        p1.setBackground(new java.awt.Color(0, 204, 204));
        p1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        p1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Project-" }));
        p1.setToolTipText("");

        sua.setBackground(new java.awt.Color(0, 153, 153));

        dt.setEditable(false);
        dt.setBackground(new java.awt.Color(0, 204, 204));
        dt.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dt.setText("District");
        dt.setMaximumSize(new java.awt.Dimension(127, 32));
        dt.setMinimumSize(new java.awt.Dimension(127, 32));
        dt.setName(""); // NOI18N
        dt.setPreferredSize(new java.awt.Dimension(127, 32));

        tt.setEditable(false);
        tt.setBackground(new java.awt.Color(0, 204, 204));
        tt.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tt.setText("Taluka");
        tt.setMaximumSize(new java.awt.Dimension(127, 32));
        tt.setMinimumSize(new java.awt.Dimension(127, 32));
        tt.setName(""); // NOI18N
        tt.setPreferredSize(new java.awt.Dimension(127, 32));

        vt.setEditable(false);
        vt.setBackground(new java.awt.Color(0, 204, 204));
        vt.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        vt.setText("Village");
        vt.setMaximumSize(new java.awt.Dimension(127, 32));
        vt.setMinimumSize(new java.awt.Dimension(127, 32));
        vt.setName(""); // NOI18N
        vt.setPreferredSize(new java.awt.Dimension(127, 32));

        sa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appoint", "Survey Agent ID", "Name", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sa.getTableHeader().setReorderingAllowed(false);
        spsa.setViewportView(sa);

        submit4.setBackground(new java.awt.Color(0, 153, 153));
        submit4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit4.setMnemonic('S');
        submit4.setText("SUBMIT");
        submit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout suaLayout = new javax.swing.GroupLayout(sua);
        sua.setLayout(suaLayout);
        suaLayout.setHorizontalGroup(
            suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suaLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(suaLayout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(submit4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(suaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(spsa, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                .addContainerGap())
        );
        suaLayout.setVerticalGroup(
            suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suaLayout.createSequentialGroup()
                .addGroup(suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(suaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(spsa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(submit4)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout app_sua1Layout = new javax.swing.GroupLayout(app_sua1);
        app_sua1.setLayout(app_sua1Layout);
        app_sua1Layout.setHorizontalGroup(
            app_sua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_sua1Layout.createSequentialGroup()
                .addGroup(app_sua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(app_sua1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(app_sua1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel15))
                    .addGroup(app_sua1Layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(submit5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(sua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        app_sua1Layout.setVerticalGroup(
            app_sua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_sua1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(app_sua1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(app_sua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, -1));

        app_flats.setBackground(new java.awt.Color(0, 153, 153));
        app_flats.setMaximumSize(new java.awt.Dimension(880, 780));
        app_flats.setMinimumSize(new java.awt.Dimension(880, 580));
        app_flats.setPreferredSize(new java.awt.Dimension(880, 580));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel14.setText("Allocate Flats");

        submit3.setBackground(new java.awt.Color(0, 153, 153));
        submit3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit3.setMnemonic('S');
        submit3.setText("SUBMIT");
        submit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit3ActionPerformed(evt);
            }
        });

        p2.setBackground(new java.awt.Color(0, 204, 204));
        p2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        p2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Project-" }));
        p2.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel22.setText("Project :");

        app_flats1.setBackground(new java.awt.Color(0, 153, 153));

        dt1.setEditable(false);
        dt1.setBackground(new java.awt.Color(0, 204, 204));
        dt1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        dt1.setText("District");
        dt1.setMaximumSize(new java.awt.Dimension(127, 32));
        dt1.setMinimumSize(new java.awt.Dimension(127, 32));
        dt1.setName(""); // NOI18N
        dt1.setPreferredSize(new java.awt.Dimension(127, 32));
        dt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt1ActionPerformed(evt);
            }
        });

        tt1.setEditable(false);
        tt1.setBackground(new java.awt.Color(0, 204, 204));
        tt1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tt1.setText("Taluka");
        tt1.setMaximumSize(new java.awt.Dimension(127, 32));
        tt1.setMinimumSize(new java.awt.Dimension(127, 32));
        tt1.setName(""); // NOI18N
        tt1.setPreferredSize(new java.awt.Dimension(127, 32));

        vt1.setEditable(false);
        vt1.setBackground(new java.awt.Color(0, 204, 204));
        vt1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        vt1.setText("Village");
        vt1.setMaximumSize(new java.awt.Dimension(127, 32));
        vt1.setMinimumSize(new java.awt.Dimension(127, 32));
        vt1.setName(""); // NOI18N
        vt1.setPreferredSize(new java.awt.Dimension(127, 32));

        sa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appoint", "Applicant_ID", "Name", "Gender", "Marital Status", "Income", "Income Group"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sa1.getTableHeader().setReorderingAllowed(false);
        spsa1.setViewportView(sa1);
        if (sa1.getColumnModel().getColumnCount() > 0) {
            sa1.getColumnModel().getColumn(0).setResizable(false);
            sa1.getColumnModel().getColumn(1).setResizable(false);
            sa1.getColumnModel().getColumn(2).setResizable(false);
            sa1.getColumnModel().getColumn(3).setResizable(false);
            sa1.getColumnModel().getColumn(4).setResizable(false);
            sa1.getColumnModel().getColumn(5).setResizable(false);
            sa1.getColumnModel().getColumn(6).setResizable(false);
        }

        submit7.setBackground(new java.awt.Color(0, 153, 153));
        submit7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit7.setMnemonic('S');
        submit7.setText("SUBMIT");
        submit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit7ActionPerformed(evt);
            }
        });

        flat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total Flats ", "Remaining"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        flat.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(flat);
        if (flat.getColumnModel().getColumnCount() > 0) {
            flat.getColumnModel().getColumn(0).setResizable(false);
            flat.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout app_flats1Layout = new javax.swing.GroupLayout(app_flats1);
        app_flats1.setLayout(app_flats1Layout);
        app_flats1Layout.setHorizontalGroup(
            app_flats1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_flats1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(dt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_flats1Layout.createSequentialGroup()
                .addComponent(spsa1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(app_flats1Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(submit7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_flats1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        app_flats1Layout.setVerticalGroup(
            app_flats1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_flats1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(app_flats1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(spsa1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(submit7)
                .addContainerGap())
        );

        javax.swing.GroupLayout app_flatsLayout = new javax.swing.GroupLayout(app_flats);
        app_flats.setLayout(app_flatsLayout);
        app_flatsLayout.setHorizontalGroup(
            app_flatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_flatsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(app_flatsLayout.createSequentialGroup()
                .addGroup(app_flatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(app_flatsLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addGroup(app_flatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel14)))
                    .addGroup(app_flatsLayout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(submit3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(app_flats1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        app_flatsLayout.setVerticalGroup(
            app_flatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_flatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(app_flatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(submit3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(app_flats1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(app_flats, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        sua.setVisible(false);
        cpr.setVisible(false);
        csmc_home.setVisible(true);
        app_flats.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        this.setVisible(false);
        login re = new login();
        re.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_log_outActionPerformed

    private void prj_repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prj_repActionPerformed
        sua.setVisible(false);
        cpr.setVisible(true);
        csmc_home.setVisible(false);
        app_flats.setVisible(false);
    p4.removeAllItems();
     conn c = new conn();
        con=c.getconn();
           System.out.println(csmc_no.getText().toString());
        String sql="select SITE_CODE from PROJECT where CSMC_CODE = '"+csmc_no.getText().toString()+"'";
        try{
            st=con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next())
            {
                String pp = rs.getString("SITE_CODE");
                System.out.println(pp);
                p4.addItem(pp);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }


// TODO add your handling code here:
    }//GEN-LAST:event_prj_repActionPerformed

    private void appt_saActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appt_saActionPerformed
        sua.setVisible(false);
        cpr.setVisible(false);
        csmc_home.setVisible(false);
        app_sua1.setVisible(true);
        p1.removeAllItems();
    
        conn c = new conn();
        con=c.getconn();
        String sql="select SITE_CODE from PROJECT where CSMC_CODE = '"+csmc_no.getText()+"' and SURVEY_AGENT_CODE is NULL";
        try{
            st=con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next())
            {
                String pp = rs.getString("SITE_CODE");
                p1.addItem(pp);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_appt_saActionPerformed

    private void appt_flatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appt_flatsActionPerformed
        app_sua1.setVisible(false);
       sua.setVisible(false);
        cpr.setVisible(false);
        csmc_home.setVisible(false);
        app_flats.setVisible(true);
        app_flats1.setVisible(false);

        p2.removeAllItems();
        conn c = new conn();
        con=c.getconn();
        String sql="select SITE_CODE from PROJECT where CSMC_CODE = '"+csmc_no.getText()+"'";
        try{
            st=con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next())
            {
                String pp = rs.getString("SITE_CODE");
                p2.addItem(pp);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_appt_flatsActionPerformed

    
    private void submit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit5ActionPerformed
        app_sua1.setVisible(false);
        cpr.setVisible(false);
        app_flats.setVisible(false);
        csmc_home.setVisible(false);
        sua.setVisible(true);
         app_flats1.setVisible(false);
     
        DefaultTableModel model = (DefaultTableModel) sa.getModel();
        model.setRowCount(0);

        conn c = new conn();
        con=c.getconn();

        String sql1="select DISTRICT,TALUKA,VILLAGE from PROJECT where SITE_CODE = '"+p1.getSelectedItem().toString()+"'";
        try{
            String dts="District";
            String vts="Village";
            String tts="Taluka";

            st=con.createStatement();
            rs = st.executeQuery(sql1);
            while(rs.next())
            {
                dts = rs.getString("DISTRICT");
                vts = rs.getString("TALUKA");
                tts = rs.getString("VILLAGE");
            }
            dt.setText(dts);
            vt.setText(vts);
            tt.setText(tts);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        String sql = "SELECT Employee_ID,First_name,Middle_name,Last_name,Gender FROM SURVEY_AGENT WHERE Employee_ID NOT IN (SELECT Agent_ID FROM Applicants) ";
        try{
            st=con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next())
            {
                String id1 = rs.getString("Employee_ID");
                String sf_name = rs.getString("First_name");
                String mf_name = rs.getString("Middle_name");
                String lf_name = rs.getString("Last_name");
                String g2 = rs.getString("Gender");

                Object[] o =  { null , id1 , sf_name+mf_name+lf_name ,g2};
                model.addRow(o);

            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_submit5ActionPerformed

    private void submit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit4ActionPerformed
        int rc = sa.getRowCount();
        int i=0;
        for( i=0;i<=rc;i++)
        {
            Boolean chked = Boolean.valueOf(sa.getValueAt(i, 0).toString());
            if(chked==true)
            break;
        }
        String dataCol1 = sa.getValueAt(i, 1).toString();

        conn c = new conn();
        con=c.getconn();
        String sql = "update PROJECT SET SURVEY_AGENT_CODE = ? WHERE  VILLAGE = '"+vt.getText()+"'    ";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1,dataCol1 );
            pst.executeUpdate();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        String sql1 = "update APPLICANTS SET Agent_ID = ? WHERE  VILLAGE = '"+vt.getText()+"'    ";
        try{
            pst = con.prepareStatement(sql1);
            pst.setString(1,dataCol1 );
            pst.executeUpdate();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        app_sua1.setVisible(false);
        cpr.setVisible(false);
        app_flats.setVisible(false);
        csmc_home.setVisible(false);
        app_flats1.setVisible(false);
        sua.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_submit4ActionPerformed

    private void submit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit3ActionPerformed
System.out.print("IN Submit");
        app_flats1.setVisible(true);        
     DefaultTableModel model2 = (DefaultTableModel) flat.getModel();
        model2.setRowCount(0);
        String vs=p2.getSelectedItem().toString();
        conn c = new conn();
        System.out.print(vs);
        con=c.getconn();

            String dt11="District";
            String vt11="Village";
            String tt11="Taluka";
            int flo=0;
            int fla=0;
        String sql1="select DISTRICT,TALUKA,VILLAGE,Floor,Flats from PROJECT where SITE_CODE=? ";
        try{
            System.out.print("IN Submit2");
            pst = con.prepareStatement(sql1);
            pst.setString(1, vs);
            rs=pst.executeQuery();
            while(rs.next())
            {
                System.out.print("IN Submit3");
                dt11 = rs.getString("DISTRICT");
                tt11 = rs.getString("TALUKA");
                vt11 = rs.getString("VILLAGE");
                flo = rs.getInt("Floor");
                fla = rs.getInt("Flats");
                System.out.print(dt11);
                System.out.print(vt11);
                System.out.print(tt11);
                System.out.print(flo);
                System.out.print(fla);
            
            }
           dt1.setText(dt11);
            vt1.setText(vt11);
            tt1.setText(tt11);
            
            Object[] o =  { fla , flo};
            model2.addRow(o);             
        }
        catch (Exception e)
        {System.out.print("IN Submit4");
            JOptionPane.showMessageDialog(null, e);
        }
        System.out.print("out Submit");
     /*   p2.removeAllItems();
        String sql="select SITE_CODE from PROJECT where CSMC_CODE = '"+csmc_no.getText()+"'";
        try{
            st=con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next())
            {
                String pp = rs.getString("SITE_CODE");
                p2.addItem(pp);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
             // TODO add your handling code here:*/
    }//GEN-LAST:event_submit3ActionPerformed

    private void submit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit7ActionPerformed
     
        int rc = sa1.getRowCount();
        int i=0;
        for( i=0;i<=rc;i++)
        {
            Boolean chked = Boolean.valueOf(sa1.getValueAt(i, 0).toString());
            if(chked==true)
            break;
        }
        String dataCol1 = sa1.getValueAt(i, 1).toString();

        conn c = new conn();
        con=c.getconn();
        //Set Trigger query by ABHIK
        String sql = "insert into CSMC_APPOINT_APPL ('"+dataCol1+"' VILLAGE = '"+p2.getSelectedItem().toString()+"')";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1,dataCol1 );
            pst.executeUpdate();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        String sql1 = "update APPLICANTS SET Agent_ID = ? WHERE  VILLAGE = '"+vt.getText()+"'    ";
        try{
            pst = con.prepareStatement(sql1);
            pst.setString(1,dataCol1 );
            pst.executeUpdate();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
p2.removeAllItems();
        String sql2="select SITE_CODE from PROJECT where CSMC_CODE = '"+csmc_no.getText()+"'";
        try{
            st=con.createStatement();
            rs = st.executeQuery(sql2);
            while(rs.next())
            {
                String pp = rs.getString("SITE_CODE");
                p2.addItem(pp);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
          app_sua1.setVisible(false);
        cpr.setVisible(false);
        csmc_home.setVisible(false);
        sua.setVisible(false);
       app_flats1.setVisible(false);
        app_flats.setVisible(true);
   
        // TODO add your handling code here:
    }//GEN-LAST:event_submit7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void dt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSMC_main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSMC_main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSMC_main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSMC_main1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CSMC_main1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel app_flats;
    private javax.swing.JPanel app_flats1;
    private javax.swing.JPanel app_sua1;
    private javax.swing.JButton appt_flats;
    private javax.swing.JButton appt_sa;
    private javax.swing.JPanel cpr;
    private javax.swing.JPanel csmc_home;
    private javax.swing.JLabel csmc_no;
    private javax.swing.JTextField dt;
    private javax.swing.JTextField dt1;
    private javax.swing.JTable flat;
    private javax.swing.JButton home;
    private javax.swing.JPanel info;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton log_out;
    private javax.swing.JComboBox<String> p1;
    private javax.swing.JComboBox<String> p2;
    private javax.swing.JComboBox<String> p4;
    private javax.swing.JButton prj_rep;
    private javax.swing.JTable sa;
    private javax.swing.JTable sa1;
    private javax.swing.JScrollPane spsa;
    private javax.swing.JScrollPane spsa1;
    private javax.swing.JPanel sua;
    private javax.swing.JButton submit3;
    private javax.swing.JButton submit4;
    private javax.swing.JButton submit5;
    private javax.swing.JButton submit7;
    private javax.swing.JTextField tt;
    private javax.swing.JTextField tt1;
    private javax.swing.JTextField vt;
    private javax.swing.JTextField vt1;
    // End of variables declaration//GEN-END:variables
}
