/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rural_housing;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhik
 */
public class MoH_main extends javax.swing.JFrame {
   Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement st = null;
    

    /**
     * Creates new form MoH_main
     */
    public MoH_main() {
        initComponents();
        v_detail.setVisible(false);
  sp.setVisible(false);
      app_company.setVisible(false);
      moh_home.setVisible(true);
      app_csmc.setVisible(false);
       view_ten.setVisible(false);
        click1.setVisible(false);
        jScrollPane2.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        moh_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        v_detail = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        state = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        district = new javax.swing.JComboBox<>();
        taluka = new javax.swing.JComboBox<>();
        village = new javax.swing.JComboBox<>();
        app_company = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        click = new javax.swing.JButton();
        state2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        district2 = new javax.swing.JComboBox<>();
        taluka2 = new javax.swing.JComboBox<>();
        village2 = new javax.swing.JComboBox<>();
        click1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        view_ten = new javax.swing.JTable();
        app_csmc = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        submit3 = new javax.swing.JButton();
        state3 = new javax.swing.JComboBox<>();
        sp = new javax.swing.JScrollPane();
        view_ag = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        view = new javax.swing.JButton();
        app_com = new javax.swing.JButton();
        home = new javax.swing.JButton();
        log_out = new javax.swing.JButton();
        app_csm = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 960));
        setMinimumSize(new java.awt.Dimension(1200, 960));
        setPreferredSize(new java.awt.Dimension(1200, 960));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 180));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 180));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rural_housing/Logo.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(417, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(330, 330, 330))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 180));
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        moh_home.setBackground(new java.awt.Color(0, 153, 153));
        moh_home.setMaximumSize(new java.awt.Dimension(820, 780));
        moh_home.setMinimumSize(new java.awt.Dimension(820, 780));
        moh_home.setPreferredSize(new java.awt.Dimension(820, 780));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 29)); // NOI18N
        jLabel2.setText("Welcome To Rural Housing Allocation System");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Ministry Of Housing Login");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout moh_homeLayout = new javax.swing.GroupLayout(moh_home);
        moh_home.setLayout(moh_homeLayout);
        moh_homeLayout.setHorizontalGroup(
            moh_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moh_homeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(moh_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        moh_homeLayout.setVerticalGroup(
            moh_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moh_homeLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(538, Short.MAX_VALUE))
        );

        getContentPane().add(moh_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        v_detail.setBackground(new java.awt.Color(0, 153, 153));
        v_detail.setMaximumSize(new java.awt.Dimension(820, 780));
        v_detail.setMinimumSize(new java.awt.Dimension(820, 780));
        v_detail.setPreferredSize(new java.awt.Dimension(820, 780));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setText("View Project Details");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("Project State:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setText("Project Village:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setText("Project District:");

        submit.setBackground(new java.awt.Color(0, 153, 153));
        submit.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit.setMnemonic('S');
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        state.setBackground(new java.awt.Color(0, 204, 204));
        state.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select State-", "Chhattisgarh", "Maharashtra", "Madhya Pradesh", "West Bengal" }));
        state.setToolTipText("");
        state.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stateItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setText("Project Taluka:");

        district.setBackground(new java.awt.Color(0, 204, 204));
        district.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select District-" }));
        district.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                districtMouseClicked(evt);
            }
        });

        taluka.setBackground(new java.awt.Color(0, 204, 204));
        taluka.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        taluka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Taluka-" }));
        taluka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                talukaMouseClicked(evt);
            }
        });

        village.setBackground(new java.awt.Color(0, 204, 204));
        village.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        village.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Village-" }));
        village.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                villageMouseClicked(evt);
            }
        });
        village.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout v_detailLayout = new javax.swing.GroupLayout(v_detail);
        v_detail.setLayout(v_detailLayout);
        v_detailLayout.setHorizontalGroup(
            v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_detailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(236, 236, 236))
            .addGroup(v_detailLayout.createSequentialGroup()
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(v_detailLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGroup(v_detailLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5)))
                        .addGap(72, 72, 72)
                        .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(village, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(district, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taluka, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(v_detailLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(submit)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        v_detailLayout.setVerticalGroup(
            v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(district, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(taluka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(v_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(village, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(submit)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        getContentPane().add(v_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 920, 720));

        app_company.setBackground(new java.awt.Color(0, 153, 153));
        app_company.setMaximumSize(new java.awt.Dimension(820, 780));
        app_company.setMinimumSize(new java.awt.Dimension(820, 780));
        app_company.setPreferredSize(new java.awt.Dimension(820, 780));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel13.setText(" Appoint Company");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setText("Project State:");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel15.setText("Project Village:");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel19.setText("Project District:");

        click.setBackground(new java.awt.Color(0, 153, 153));
        click.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        click.setMnemonic('C');
        click.setText("Click to get Tenders for Project");
        click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });

        state2.setBackground(new java.awt.Color(0, 204, 204));
        state2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        state2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select State-", "Chhattisgarh", "Maharashtra", "Madhya Pradesh", "West Bengal" }));
        state2.setToolTipText("");
        state2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                state2ItemStateChanged(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel20.setText("Project Taluka:");

        district2.setBackground(new java.awt.Color(0, 204, 204));
        district2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        district2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select District-" }));
        district2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                district2MouseClicked(evt);
            }
        });

        taluka2.setBackground(new java.awt.Color(0, 204, 204));
        taluka2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        taluka2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Taluka-" }));
        taluka2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taluka2MouseClicked(evt);
            }
        });

        village2.setBackground(new java.awt.Color(0, 204, 204));
        village2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        village2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Village-" }));
        village2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                village2MouseClicked(evt);
            }
        });
        village2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                village2ActionPerformed(evt);
            }
        });

        click1.setBackground(new java.awt.Color(0, 153, 153));
        click1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        click1.setMnemonic('S');
        click1.setText("Submit");
        click1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                click1ActionPerformed(evt);
            }
        });

        view_ten.setBackground(new java.awt.Color(0, 153, 153));
        view_ten.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        view_ten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Allocate", "UID_No", "Name", "Status", "Experience"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        view_ten.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        view_ten.getTableHeader().setResizingAllowed(false);
        view_ten.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(view_ten);
        if (view_ten.getColumnModel().getColumnCount() > 0) {
            view_ten.getColumnModel().getColumn(0).setResizable(false);
            view_ten.getColumnModel().getColumn(0).setPreferredWidth(10);
            view_ten.getColumnModel().getColumn(1).setResizable(false);
            view_ten.getColumnModel().getColumn(1).setPreferredWidth(20);
            view_ten.getColumnModel().getColumn(2).setResizable(false);
            view_ten.getColumnModel().getColumn(2).setPreferredWidth(80);
            view_ten.getColumnModel().getColumn(3).setResizable(false);
            view_ten.getColumnModel().getColumn(3).setPreferredWidth(40);
            view_ten.getColumnModel().getColumn(4).setResizable(false);
            view_ten.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        javax.swing.GroupLayout app_companyLayout = new javax.swing.GroupLayout(app_company);
        app_company.setLayout(app_companyLayout);
        app_companyLayout.setHorizontalGroup(
            app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_companyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(click1)
                .addGap(355, 355, 355))
            .addGroup(app_companyLayout.createSequentialGroup()
                .addGroup(app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(app_companyLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addGroup(app_companyLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel15)))
                        .addGap(72, 72, 72)
                        .addGroup(app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(village2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(district2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taluka2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(app_companyLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel13))
                    .addGroup(app_companyLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(click))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        app_companyLayout.setVerticalGroup(
            app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_companyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(state2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(district2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(taluka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(app_companyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(village2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(click)
                .addGap(96, 96, 96)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(click1)
                .addGap(54, 54, 54))
        );

        getContentPane().add(app_company, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        app_csmc.setBackground(new java.awt.Color(0, 153, 153));
        app_csmc.setMaximumSize(new java.awt.Dimension(820, 780));
        app_csmc.setMinimumSize(new java.awt.Dimension(820, 780));
        app_csmc.setPreferredSize(new java.awt.Dimension(820, 780));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel21.setText(" Appoint CSMC Agent");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel22.setText(" State:");

        submit3.setBackground(new java.awt.Color(0, 153, 153));
        submit3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit3.setMnemonic('S');
        submit3.setText("SUBMIT");
        submit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit3ActionPerformed(evt);
            }
        });

        state3.setBackground(new java.awt.Color(0, 204, 204));
        state3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        state3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select State-", "Chhattisgarh", "Maharashtra", "Madhya Pradesh", "West Bengal" }));
        state3.setToolTipText("");
        state3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                state3ItemStateChanged(evt);
            }
        });

        sp.setBackground(new java.awt.Color(0, 153, 153));
        sp.setBorder(null);

        view_ag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "code", "f_name", "m_name", "l_name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        view_ag.getTableHeader().setReorderingAllowed(false);
        sp.setViewportView(view_ag);
        if (view_ag.getColumnModel().getColumnCount() > 0) {
            view_ag.getColumnModel().getColumn(0).setResizable(false);
            view_ag.getColumnModel().getColumn(1).setResizable(false);
            view_ag.getColumnModel().getColumn(2).setResizable(false);
            view_ag.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout app_csmcLayout = new javax.swing.GroupLayout(app_csmc);
        app_csmc.setLayout(app_csmcLayout);
        app_csmcLayout.setHorizontalGroup(
            app_csmcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_csmcLayout.createSequentialGroup()
                .addGroup(app_csmcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(app_csmcLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(submit3))
                    .addGroup(app_csmcLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(app_csmcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(app_csmcLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(75, 75, 75)
                                .addComponent(state3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, app_csmcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(232, 232, 232))
        );
        app_csmcLayout.setVerticalGroup(
            app_csmcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(app_csmcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(app_csmcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(state3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(55, 55, 55)
                .addComponent(submit3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
        );

        getContentPane().add(app_csmc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 920, 720));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(380, 780));
        jPanel1.setMinimumSize(new java.awt.Dimension(380, 780));
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 780));

        view.setBackground(new java.awt.Color(0, 204, 204));
        view.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        view.setMnemonic('V');
        view.setText("View Project Details");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        app_com.setBackground(new java.awt.Color(0, 204, 204));
        app_com.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        app_com.setMnemonic('A');
        app_com.setText("Appoint Company");
        app_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_comActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 204, 204));
        home.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        home.setMnemonic('H');
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        log_out.setBackground(new java.awt.Color(0, 204, 204));
        log_out.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        log_out.setMnemonic('L');
        log_out.setText("Log Out");
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });

        app_csm.setBackground(new java.awt.Color(0, 204, 204));
        app_csm.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        app_csm.setMnemonic('C');
        app_csm.setText("Appoint CSMC Agent");
        app_csm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_csmActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setText("MoH Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(app_com, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(log_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82))
                    .addComponent(app_csm, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(view)
                .addGap(50, 50, 50)
                .addComponent(app_com)
                .addGap(51, 51, 51)
                .addComponent(app_csm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(home)
                .addGap(50, 50, 50)
                .addComponent(log_out)
                .addGap(83, 83, 83))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

    }//GEN-LAST:event_submitActionPerformed

    private void stateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stateItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stateItemStateChanged

    private void villageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_villageActionPerformed

    private void clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickActionPerformed
        view_ten.setVisible(true);
        click1.setVisible(true);        
        jScrollPane2.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) view_ten.getModel();
        model.setRowCount(0);
        conn c = new conn();
        con=c.getconn();
        String vill = village2.getSelectedItem().toString();
        String sql = "SELECT Company_ID,Status,Name,Experience FROM COMPANY WHERE Company_ID IN (SELECT com FROM TENDER WHERE project = ( SELECT SITE_CODE from PROJECT WHERE VILLAGE = '"+vill+"' ) )  ORDER BY Status , Experience DESC ";
         try{
                st=con.createStatement();
                rs = st.executeQuery(sql);
                while(rs.next())
                {
                    String code = rs.getString("Company_ID");
                    String sf_name = rs.getString("Status");
                    String name = rs.getString("Name");
                    int exp = rs.getInt("Experience");
                    
                    Object[] o =  { null , code , name ,sf_name,exp};
                    model.addRow(o);
                    
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
          
        // TODO add your handling code here:
    }//GEN-LAST:event_clickActionPerformed

    private void state2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_state2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_state2ItemStateChanged

    private void village2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_village2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_village2ActionPerformed

    private void submit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit3ActionPerformed
       sp.setVisible(true);
        conn c = new conn();
        con=c.getconn();
      
        String query = "select * from csmc_table_name where state = ? ";
        try
        {
          pst = con.prepareStatement(query);
          pst.setString(1, state3.getSelectedItem().toString());


            while (rs.next()) {
                String code = rs.getString("csmc_code");
                String sf_name = rs.getString("f_name");
                String sm_name = rs.getString("m_name");
                String sl_name = rs.getString("l_name");
                //String code = "csmc_code";
                //String sf_name = "f_name";
                //String sm_name = "m_name";
                //String sl_name = "l_name";  
                Object[] o =  {code, sf_name, sm_name,sl_name};
                DefaultTableModel model = (DefaultTableModel) view_ag.getModel();
                model.addRow(o);
                
               
            }

        
        }
          catch (Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submit3ActionPerformed

    private void state3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_state3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_state3ItemStateChanged

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        v_detail.setVisible(false);
        
      moh_home.setVisible(false);
      app_company.setVisible(false);
      app_csmc.setVisible(false);
        v_detail.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void app_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_comActionPerformed
                v_detail.setVisible(false);
      app_company.setVisible(false);
      app_csmc.setVisible(false);
      moh_home.setVisible(false);
       app_company.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_app_comActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
                v_detail.setVisible(false);
      app_company.setVisible(false);
      app_csmc.setVisible(false);
      moh_home.setVisible(false);
      moh_home.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        this.setVisible(false);
        login re = new login();
        re.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_log_outActionPerformed

    private void app_csmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_csmActionPerformed
                v_detail.setVisible(false);
      app_company.setVisible(false);
      app_csmc.setVisible(false);
      moh_home.setVisible(false);
       app_csmc.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_app_csmActionPerformed

    private void click1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_click1ActionPerformed
        int rc = view_ten.getRowCount();
        int i=0;
        for( i=0;i<=rc;i++)
        {
            Boolean chked = Boolean.valueOf(view_ten.getValueAt(i, 0).toString());
            if(chked==true)
                break;
        }
        String dataCol1 = view_ten.getValueAt(i, 1).toString();
        
        String vill = village2.getSelectedItem().toString();
        JOptionPane.showMessageDialog(null, "Company Appointed for Project\nTender Accepted");
        v_detail.setVisible(false);
      app_company.setVisible(false);
      app_csmc.setVisible(false);
      
       app_csmc.setVisible(false);
       moh_home.setVisible(true);
       conn c = new conn();
        con=c.getconn();
        String sql = "update PROJECT SET COMPANY_CODE = ? WHERE  VILLAGE = '"+vill+"'    ";
         try{
                pst = con.prepareStatement(sql);
                pst.setString(1,dataCol1 );
                pst.executeUpdate();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
      v_detail.setVisible(false);
      app_company.setVisible(false);
      app_csmc.setVisible(false);
      moh_home.setVisible(false);
      moh_home.setVisible(true);
         // TODO add your handling code here:
    }//GEN-LAST:event_click1ActionPerformed

    private void village2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_village2MouseClicked
     if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Deulgaon Raja"))
        {
            village2.removeAllItems();
            village2.addItem("Aaland");
            village2.addItem("Umbarkhed");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Lonar"))
        {
            village2.removeAllItems();
            village2.addItem("Hirdav");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            village2.removeAllItems();
            village2.addItem("Matori");
            village2.addItem("Dari");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Shirpur"))
        {
            village2.removeAllItems();
            village2.addItem("Jalod");
            village2.addItem("Mandal");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Marwahi"))
        {
            village2.removeAllItems();
            village2.addItem("Dhanpur");
            village2.addItem("Lohari");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Pali"))
        {
            village2.removeAllItems();
            village2.addItem("Batra");
            village2.addItem("Sirli");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Arang"))
        {
            village2.removeAllItems();
            village2.addItem("Ameri");
            village2.addItem("Nisda");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Haripal"))
        {
            village2.removeAllItems();
            village2.addItem("Kaikala");
            village2.addItem("Jejur");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Nanoor"))
        {
            village2.removeAllItems();
            village2.addItem("Thupsara");
            village2.addItem("Jalundi");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Kulpi"))
        {
            village2.removeAllItems();
            village2.addItem("Dhola");
            village2.addItem("Ramkishore");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Bagh"))
        {
            village2.removeAllItems();
            village2.addItem("Devdha");
            village2.addItem("Jali");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Aron"))
        {
            village2.removeAllItems();
            village2.addItem("Davri");
            village2.addItem("Patan");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Gunor"))
        {
            village2.removeAllItems();
            village2.addItem("Ganj");
            village2.addItem("Kamtana");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Tilda"))
        {
            village2.removeAllItems();
            village2.addItem("Bhiloni");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Labpur"))
        {
            village2.removeAllItems();
            village2.addItem("Jamna");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Chanchoda"))
        {
            village2.removeAllItems();
            village2.addItem("Murela");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Bamori"))
        {
            village2.removeAllItems();
            village2.addItem("Rampur");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_village2MouseClicked

    private void district2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_district2MouseClicked
   if(state2.getSelectedItem().toString().equalsIgnoreCase("Maharashtra"))
        {
            district2.removeAllItems();
            district2.addItem("Buldhana");
            district2.addItem("Nashik");
            district2.addItem("Dhule");
        }
        else if(state2.getSelectedItem().toString().equalsIgnoreCase("Chhattisgarh"))
        {
            district2.removeAllItems();
            district2.addItem("Bilaspur");
            district2.addItem("Korba");
            district2.addItem("Raipur");
        }
        else if(state2.getSelectedItem().toString().equalsIgnoreCase("West Bengal"))
        {
            district2.removeAllItems();
            district2.addItem("Hoogly");
            district2.addItem("Birbhum");
            district2.addItem("South 24 Parganas");
        }
        else if(state2.getSelectedItem().toString().equalsIgnoreCase("Madhya pradesh"))
        {
            district2.removeAllItems();
            district2.addItem("Dhar");
            district2.addItem("Guna");
            district2.addItem("Panna");
        }   // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_district2MouseClicked

    private void taluka2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taluka2MouseClicked
if(district2.getSelectedItem().toString().equalsIgnoreCase("Buldhana"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Deulgaon Raja");
            taluka2.addItem("Lonar");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Nashik");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Dhule"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Shirpur");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Bilaspur"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Marwani");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Korba"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Pali");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Raipur"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Arang");
            taluka2.addItem("Tilda");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Hoogly"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Haripal");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Birbhum"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Nanoor");
            taluka2.addItem("Labpur");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("South 24 Paraganas"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Kulpi");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Dhar"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Bagh");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Guna"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Aron");
            taluka2.addItem("Chanchoda");
            taluka2.addItem("Bamori");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Panna"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Gunor");
        }    // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_taluka2MouseClicked

    private void districtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_districtMouseClicked
        if(state2.getSelectedItem().toString().equalsIgnoreCase("Maharashtra"))
        {
            district2.removeAllItems();
            district2.addItem("Buldhana");
            district2.addItem("Nashik");
            district2.addItem("Dhule");
        }
        else if(state2.getSelectedItem().toString().equalsIgnoreCase("Chhattisgarh"))
        {
            district2.removeAllItems();
            district2.addItem("Bilaspur");
            district2.addItem("Korba");
            district2.addItem("Raipur");
        }
        else if(state2.getSelectedItem().toString().equalsIgnoreCase("West Bengal"))
        {
            district2.removeAllItems();
            district2.addItem("Hoogly");
            district2.addItem("Birbhum");
            district2.addItem("South 24 Parganas");
        }
        else if(state2.getSelectedItem().toString().equalsIgnoreCase("Madhya pradesh"))
        {
            district2.removeAllItems();
            district2.addItem("Dhar");
            district2.addItem("Guna");
            district2.addItem("Panna");
        }   // TODO add your handling code here:        // TODO add your handling code here:  // TODO add your handling code here:
    }//GEN-LAST:event_districtMouseClicked

    private void talukaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_talukaMouseClicked
      if(district2.getSelectedItem().toString().equalsIgnoreCase("Buldhana"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Deulgaon Raja");
            taluka2.addItem("Lonar");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Nashik");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Dhule"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Shirpur");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Bilaspur"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Marwani");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Korba"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Pali");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Raipur"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Arang");
            taluka2.addItem("Tilda");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Hoogly"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Haripal");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Birbhum"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Nanoor");
            taluka2.addItem("Labpur");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("South 24 Paraganas"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Kulpi");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Dhar"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Bagh");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Guna"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Aron");
            taluka2.addItem("Chanchoda");
            taluka2.addItem("Bamori");
        }
        else if(district2.getSelectedItem().toString().equalsIgnoreCase("Panna"))
        {
            taluka2.removeAllItems();
            taluka2.addItem("Gunor");
        }    // TODO add your handling code here:        // TODO add your handling code here:  // TODO add your handling code here:
    }//GEN-LAST:event_talukaMouseClicked

    private void villageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_villageMouseClicked
       if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Deulgaon Raja"))
        {
            village2.removeAllItems();
            village2.addItem("Aaland");
            village2.addItem("Umbarkhed");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Lonar"))
        {
            village2.removeAllItems();
            village2.addItem("Hirdav");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Nashik"))
        {
            village2.removeAllItems();
            village2.addItem("Matori");
            village2.addItem("Dari");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Shirpur"))
        {
            village2.removeAllItems();
            village2.addItem("Jalod");
            village2.addItem("Mandal");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Marwahi"))
        {
            village2.removeAllItems();
            village2.addItem("Dhanpur");
            village2.addItem("Lohari");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Pali"))
        {
            village2.removeAllItems();
            village2.addItem("Batra");
            village2.addItem("Sirli");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Arang"))
        {
            village2.removeAllItems();
            village2.addItem("Ameri");
            village2.addItem("Nisda");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Haripal"))
        {
            village2.removeAllItems();
            village2.addItem("Kaikala");
            village2.addItem("Jejur");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Nanoor"))
        {
            village2.removeAllItems();
            village2.addItem("Thupsara");
            village2.addItem("Jalundi");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Kulpi"))
        {
            village2.removeAllItems();
            village2.addItem("Dhola");
            village2.addItem("Ramkishore");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Bagh"))
        {
            village2.removeAllItems();
            village2.addItem("Devdha");
            village2.addItem("Jali");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Aron"))
        {
            village2.removeAllItems();
            village2.addItem("Davri");
            village2.addItem("Patan");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Gunor"))
        {
            village2.removeAllItems();
            village2.addItem("Ganj");
            village2.addItem("Kamtana");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Tilda"))
        {
            village2.removeAllItems();
            village2.addItem("Bhiloni");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Labpur"))
        {
            village2.removeAllItems();
            village2.addItem("Jamna");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Chanchoda"))
        {
            village2.removeAllItems();
            village2.addItem("Murela");
        }
        else if(taluka2.getSelectedItem().toString().equalsIgnoreCase("Bamori"))
        {
            village2.removeAllItems();
            village2.addItem("Rampur");
        }   // TODO add your handling code here: // TODO add your handling code here:
    }//GEN-LAST:event_villageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoH_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoH_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoH_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoH_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoH_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton app_com;
    private javax.swing.JPanel app_company;
    private javax.swing.JButton app_csm;
    private javax.swing.JPanel app_csmc;
    private javax.swing.JButton click;
    private javax.swing.JButton click1;
    private javax.swing.JComboBox<String> district;
    private javax.swing.JComboBox<String> district2;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton log_out;
    private javax.swing.JPanel moh_home;
    private javax.swing.JScrollPane sp;
    private javax.swing.JComboBox<String> state;
    private javax.swing.JComboBox<String> state2;
    private javax.swing.JComboBox<String> state3;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit3;
    private javax.swing.JComboBox<String> taluka;
    private javax.swing.JComboBox<String> taluka2;
    private javax.swing.JPanel v_detail;
    private javax.swing.JButton view;
    private javax.swing.JTable view_ag;
    private javax.swing.JTable view_ten;
    private javax.swing.JComboBox<String> village;
    private javax.swing.JComboBox<String> village2;
    // End of variables declaration//GEN-END:variables
}
