/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rural_housing;

import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Abhik
 */
public class survey_agent_main extends javax.swing.JFrame {
Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement st = null;
    /**
     * Creates new form survey_agent_main
     */
    public survey_agent_main() {
        initComponents();
        s_agent_home.setVisible(false); 
        reg_sp.setVisible(false); 
        app_sp.setVisible(false);
        s_agent_home.setVisible(true);
       ac.add(acy);
        ac.add(acn);
        bc.add(bcy);
        bc.add(bcn);
        ic.add(icy);
        ic.add(icn);
        rc.add(rcy);
        rc.add(rcy);
        mc.add(dcy);
        mc.add(mcn);
        dc.add(dcy);
        dc.add(dcn);
    }
public survey_agent_main(String aa) {
        initComponents();
        s_agent_home.setVisible(false); 
        reg_sp.setVisible(false); 
        app_sp.setVisible(false);
        s_agent_home.setVisible(true);
         ac.add(acy);
        ac.add(acn);
        bc.add(bcy);
        bc.add(bcn);
        ic.add(icy);
        ic.add(icn);
        rc.add(rcy);
        rc.add(rcy);
        mc.add(dcy);
        mc.add(mcn);
        dc.add(dcy);
        dc.add(dcn);
     sag_no.setText(aa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ac = new javax.swing.ButtonGroup();
        bc = new javax.swing.ButtonGroup();
        ic = new javax.swing.ButtonGroup();
        rc = new javax.swing.ButtonGroup();
        mc = new javax.swing.ButtonGroup();
        dc = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        s_agent_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sag_no = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        view_det1 = new javax.swing.JButton();
        home1 = new javax.swing.JButton();
        log_out1 = new javax.swing.JButton();
        sur_reg = new javax.swing.JButton();
        sur_app = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        app_sp = new javax.swing.JScrollPane();
        s_rep_app = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        app_no = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mcy = new javax.swing.JRadioButton();
        bcn = new javax.swing.JRadioButton();
        icy = new javax.swing.JRadioButton();
        bcy = new javax.swing.JRadioButton();
        acy = new javax.swing.JRadioButton();
        icn = new javax.swing.JRadioButton();
        mcn = new javax.swing.JRadioButton();
        acn = new javax.swing.JRadioButton();
        v = new javax.swing.JComboBox<>();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        dcy = new javax.swing.JRadioButton();
        dcn = new javax.swing.JRadioButton();
        jLabel73 = new javax.swing.JLabel();
        rcy = new javax.swing.JRadioButton();
        rcn = new javax.swing.JRadioButton();
        jLabel74 = new javax.swing.JLabel();
        submit2 = new javax.swing.JButton();
        reg_sp = new javax.swing.JScrollPane();
        s_rep_reg = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        submit1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        gdp = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        nof = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        landtype = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        remark = new javax.swing.JTextArea();
        app_no1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 960));
        setMinimumSize(new java.awt.Dimension(1200, 760));
        setPreferredSize(new java.awt.Dimension(1200, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 180));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rural_housing/Logo.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(330, 330, 330))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 180));

        s_agent_home.setBackground(new java.awt.Color(0, 153, 153));
        s_agent_home.setMaximumSize(new java.awt.Dimension(870, 580));
        s_agent_home.setMinimumSize(new java.awt.Dimension(870, 550));
        s_agent_home.setPreferredSize(new java.awt.Dimension(870, 580));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 29)); // NOI18N
        jLabel2.setText("Welcome To Rural Housing Allocation System.");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setText("Survey Agent Login");

        sag_no.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        sag_no.setText("Label");

        javax.swing.GroupLayout s_agent_homeLayout = new javax.swing.GroupLayout(s_agent_home);
        s_agent_home.setLayout(s_agent_homeLayout);
        s_agent_homeLayout.setHorizontalGroup(
            s_agent_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_agent_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(s_agent_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, s_agent_homeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, s_agent_homeLayout.createSequentialGroup()
                        .addGroup(s_agent_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addGroup(s_agent_homeLayout.createSequentialGroup()
                                .addComponent(sag_no)
                                .addGap(84, 84, 84)))
                        .addGap(298, 298, 298))))
        );
        s_agent_homeLayout.setVerticalGroup(
            s_agent_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_agent_homeLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sag_no, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(368, 368, 368))
        );

        getContentPane().add(s_agent_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 830, -1));

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setMaximumSize(new java.awt.Dimension(370, 780));
        jPanel5.setMinimumSize(new java.awt.Dimension(370, 550));
        jPanel5.setPreferredSize(new java.awt.Dimension(370, 580));

        view_det1.setBackground(new java.awt.Color(0, 204, 204));
        view_det1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        view_det1.setMnemonic('V');
        view_det1.setText("View Agent Details");
        view_det1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_det1ActionPerformed(evt);
            }
        });

        home1.setBackground(new java.awt.Color(0, 204, 204));
        home1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        home1.setMnemonic('H');
        home1.setText("Home");
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });

        log_out1.setBackground(new java.awt.Color(0, 204, 204));
        log_out1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        log_out1.setMnemonic('L');
        log_out1.setText("Log Out");
        log_out1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out1ActionPerformed(evt);
            }
        });

        sur_reg.setBackground(new java.awt.Color(0, 204, 204));
        sur_reg.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        sur_reg.setMnemonic('S');
        sur_reg.setText("Survey Report (Region)");
        sur_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sur_regActionPerformed(evt);
            }
        });

        sur_app.setBackground(new java.awt.Color(0, 204, 204));
        sur_app.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        sur_app.setMnemonic('R');
        sur_app.setText("Survey Report (Applicant)");
        sur_app.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sur_appActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setText("Survey Agent Login");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(view_det1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sur_reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sur_app, javax.swing.GroupLayout.PREFERRED_SIZE, 346, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(log_out1)
                            .addComponent(home1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(68, 68, 68))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(view_det1)
                .addGap(36, 36, 36)
                .addComponent(sur_reg)
                .addGap(35, 35, 35)
                .addComponent(sur_app)
                .addGap(102, 102, 102)
                .addComponent(home1)
                .addGap(49, 49, 49)
                .addComponent(log_out1)
                .addGap(87, 87, 87))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 370, -1));

        app_sp.setMaximumSize(new java.awt.Dimension(870, 780));
        app_sp.setMinimumSize(new java.awt.Dimension(870, 550));
        app_sp.setPreferredSize(new java.awt.Dimension(870, 550));

        s_rep_app.setBackground(new java.awt.Color(0, 153, 153));
        s_rep_app.setMaximumSize(new java.awt.Dimension(870, 780));
        s_rep_app.setMinimumSize(new java.awt.Dimension(870, 580));
        s_rep_app.setPreferredSize(new java.awt.Dimension(870, 580));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setText("Survey Report (Applicant)");

        submit.setBackground(new java.awt.Color(0, 153, 153));
        submit.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit.setMnemonic('S');
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel7.setText("Applicant Number:");

        app_no.setBackground(new java.awt.Color(0, 204, 204));
        app_no.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        app_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        app_no.setText("Project No");
        app_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_noActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel10.setText("Document Name");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel11.setText("Status");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel8.setText("Aadhar Card:");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel12.setText("Birth Certificate:");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel9.setText("Income Certificate:");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel15.setText("Marriage Certificate:");

        mcy.setBackground(new java.awt.Color(0, 153, 153));
        mcy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcy.setText("Submitted");

        bcn.setBackground(new java.awt.Color(0, 153, 153));
        bcn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bcn.setText("Not Submitted");

        icy.setBackground(new java.awt.Color(0, 153, 153));
        icy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        icy.setText("Submitted");

        bcy.setBackground(new java.awt.Color(0, 153, 153));
        bcy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bcy.setText("Submitted");

        acy.setBackground(new java.awt.Color(0, 153, 153));
        acy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        acy.setText("Submitted");

        icn.setBackground(new java.awt.Color(0, 153, 153));
        icn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        icn.setText("Not Submitted");

        mcn.setBackground(new java.awt.Color(0, 153, 153));
        mcn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        mcn.setText("Not Submitted");

        acn.setBackground(new java.awt.Color(0, 153, 153));
        acn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        acn.setText("Not Submitted");

        v.setBackground(new java.awt.Color(0, 204, 204));
        v.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        v.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Applicant number-" }));

        jLabel82.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel82.setText("Death Certificate");

        jLabel83.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel83.setText("(for widowed applicant only)");

        dcy.setBackground(new java.awt.Color(0, 153, 153));
        dcy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        dcy.setText("Submitted");

        dcn.setBackground(new java.awt.Color(0, 153, 153));
        dcn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        dcn.setText("Not Submitted");

        jLabel73.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel73.setText("(if applicable)");

        rcy.setBackground(new java.awt.Color(0, 153, 153));
        rcy.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        rcy.setText("Submitted");

        rcn.setBackground(new java.awt.Color(0, 153, 153));
        rcn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        rcn.setText("Not Submitted");

        jLabel74.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel74.setText("Ration Card ");

        submit2.setBackground(new java.awt.Color(0, 153, 153));
        submit2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit2.setMnemonic('S');
        submit2.setText("SUBMIT");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout s_rep_appLayout = new javax.swing.GroupLayout(s_rep_app);
        s_rep_app.setLayout(s_rep_appLayout);
        s_rep_appLayout.setHorizontalGroup(
            s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_rep_appLayout.createSequentialGroup()
                .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(s_rep_appLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel3))
                    .addGroup(s_rep_appLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel10))
                    .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, s_rep_appLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submit2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, s_rep_appLayout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel83)
                                .addComponent(jLabel8)
                                .addComponent(jLabel12)
                                .addComponent(jLabel9)
                                .addComponent(jLabel15)
                                .addComponent(jLabel73)
                                .addComponent(jLabel82)
                                .addComponent(jLabel74))
                            .addGap(53, 53, 53)
                            .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(submit)
                                .addGroup(s_rep_appLayout.createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addComponent(jLabel11))
                                .addGroup(s_rep_appLayout.createSequentialGroup()
                                    .addComponent(icy)
                                    .addGap(18, 18, 18)
                                    .addComponent(icn))
                                .addGroup(s_rep_appLayout.createSequentialGroup()
                                    .addComponent(bcy)
                                    .addGap(18, 18, 18)
                                    .addComponent(bcn))
                                .addGroup(s_rep_appLayout.createSequentialGroup()
                                    .addComponent(mcy)
                                    .addGap(18, 18, 18)
                                    .addComponent(mcn))
                                .addGroup(s_rep_appLayout.createSequentialGroup()
                                    .addComponent(acy)
                                    .addGap(18, 18, 18)
                                    .addComponent(acn))
                                .addGroup(s_rep_appLayout.createSequentialGroup()
                                    .addComponent(rcy)
                                    .addGap(18, 18, 18)
                                    .addComponent(rcn))
                                .addGroup(s_rep_appLayout.createSequentialGroup()
                                    .addComponent(dcy)
                                    .addGap(18, 18, 18)
                                    .addComponent(dcn))))))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, s_rep_appLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(app_no, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(315, 315, 315))
        );
        s_rep_appLayout.setVerticalGroup(
            s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_rep_appLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(app_no, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit2))
                .addGap(18, 18, 18)
                .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(acy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bcy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bcn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(s_rep_appLayout.createSequentialGroup()
                        .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(icy)
                            .addComponent(icn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rcn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rcy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(s_rep_appLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel74)
                        .addGap(8, 8, 8)))
                .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mcy)
                        .addComponent(mcn)))
                .addGap(0, 0, 0)
                .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(s_rep_appLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submit))
                    .addGroup(s_rep_appLayout.createSequentialGroup()
                        .addComponent(jLabel73)
                        .addGap(18, 18, 18)
                        .addGroup(s_rep_appLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcy)
                            .addComponent(dcn))
                        .addComponent(jLabel83)
                        .addContainerGap(55, Short.MAX_VALUE))))
        );

        app_sp.setViewportView(s_rep_app);

        getContentPane().add(app_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        reg_sp.setMaximumSize(new java.awt.Dimension(870, 780));
        reg_sp.setMinimumSize(new java.awt.Dimension(830, 580));
        reg_sp.setPreferredSize(new java.awt.Dimension(832, 580));

        s_rep_reg.setBackground(new java.awt.Color(0, 153, 153));
        s_rep_reg.setMaximumSize(new java.awt.Dimension(830, 580));
        s_rep_reg.setMinimumSize(new java.awt.Dimension(830, 550));
        s_rep_reg.setPreferredSize(new java.awt.Dimension(830, 550));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel14.setText("Survey Report (Region)");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N

        submit1.setBackground(new java.awt.Color(0, 153, 153));
        submit1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submit1.setMnemonic('S');
        submit1.setText("SUBMIT");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel21.setText("GDP Of The Region:");

        gdp.setBackground(new java.awt.Color(0, 204, 204));
        gdp.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        gdp.setText("Enter The GDP Of The Region");
        gdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdpActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel22.setText("Number Of Families:");

        nof.setBackground(new java.awt.Color(0, 204, 204));
        nof.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nof.setText("Enter The Number Of Families");
        nof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nofActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel23.setText("Land Type Of Region:");

        landtype.setBackground(new java.awt.Color(0, 204, 204));
        landtype.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        landtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agricultural", "Barren", "Industrial", "Residential", "Other" }));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel24.setText("Remarks (if any):");

        remark.setBackground(new java.awt.Color(0, 204, 204));
        remark.setColumns(20);
        remark.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        remark.setRows(5);
        remark.setText("\n");
        jScrollPane2.setViewportView(remark);

        app_no1.setBackground(new java.awt.Color(0, 204, 204));
        app_no1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        app_no1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        app_no1.setText("Project No");
        app_no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                app_no1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout s_rep_regLayout = new javax.swing.GroupLayout(s_rep_reg);
        s_rep_reg.setLayout(s_rep_regLayout);
        s_rep_regLayout.setHorizontalGroup(
            s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_rep_regLayout.createSequentialGroup()
                .addGroup(s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(s_rep_regLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(s_rep_regLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel24)
                                .addGap(127, 127, 127)
                                .addGroup(s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gdp)
                                    .addComponent(nof)
                                    .addComponent(landtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))
                            .addGroup(s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23))
                            .addGroup(s_rep_regLayout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(app_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(s_rep_regLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(submit1))
                    .addGroup(s_rep_regLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel14)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        s_rep_regLayout.setVerticalGroup(
            s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(s_rep_regLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(app_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(54, 54, 54)
                .addGroup(s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(gdp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(nof, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(landtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(s_rep_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(submit1)
                .addGap(146, 146, 146))
        );

        reg_sp.setViewportView(s_rep_reg);

        getContentPane().add(reg_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view_det1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_det1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_det1ActionPerformed

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
  reg_sp.setVisible(false);
        s_agent_home.setVisible(false); 
        app_sp.setVisible(false);
    s_agent_home.setVisible(true); 
      
    }//GEN-LAST:event_home1ActionPerformed

    private void log_out1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out1ActionPerformed
        this.setVisible(false);
        login re = new login();
        re.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_log_out1ActionPerformed

    private void sur_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sur_regActionPerformed
        s_agent_home.setVisible(false); 
      reg_sp.setVisible(false);
        app_sp.setVisible(false);
      reg_sp.setVisible(true);
    }//GEN-LAST:event_sur_regActionPerformed

    private void sur_appActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sur_appActionPerformed
      reg_sp.setVisible(false);
        s_agent_home.setVisible(false); 
        app_sp.setVisible(false);
      app_sp.setVisible(true);
    }//GEN-LAST:event_sur_appActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        conn c = new conn();
        con=c.getconn();
       
        String gender,ms_pass,mc_pass="NOT APPLICABLE",rc_pass,ac_pass,bc_pass,ic_pass,dc_pass="NOT APPLICABLE";
        
            if(mcy.isSelected())
            {
                mc_pass = "YES";
            }
            else
            {
                mc_pass = "NO";
            }
        
            if(dcy.isSelected())
            {
                dc_pass = "YES";
            }
            else if(dcn.isSelected())
            {
                dc_pass = "NO";
            }
        
        if(acy.isSelected())
        {
            ac_pass = "YES";
        }
        else
        {
            ac_pass = "NO";
        }

        if(bcy.isSelected())
        {
            bc_pass = "YES";
        }
        else
        {
            bc_pass = "NO";
        }
        if(icy.isSelected())
        {
            ic_pass = "YES";
        }
        else
        {
            ic_pass = "NO";
        }

        if(rcy.isSelected())
        {
            rc_pass = "YES";
        }
        else
        {
            rc_pass = "NO";
        }
          String q2 = "insert into APPL_DOCS_SUBMIT(aadhar_copy,birth_cert_copy,income_cert_copy,ration_copy,marriage_copy,death_copy,appl_num)  values(?,?,?,?,?,?,?)";
        try
        {
            pst = con.prepareStatement(q2);

            pst.setObject(1,ac_pass);
            pst.setString(2,bc_pass);
            pst.setString(3,ic_pass);
            pst.setString(4,rc_pass);
            pst.setString(5, mc_pass);
            pst.setString(6, dc_pass);
            pst.setString(7,v.getSelectedItem().toString());
           
            pst.execute();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }   
            
          
    }//GEN-LAST:event_submitActionPerformed

    private void app_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_app_noActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed

    }//GEN-LAST:event_submit1ActionPerformed

    private void gdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gdpActionPerformed

    private void nofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nofActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
    conn c = new conn();
    con=c.getconn();
   
   String mc_pass,rc_pass,ac_pass,bc_pass,ic_pass,dc_pass;
        String q2 = "select aadhar_copy,birth_cert_copy,income_cert_copy,ration_copy,marriage_copy,death_copy from APPL_DOCS_SUBMIT where appl_num='"+app_no.getText()+"'";
        try
        {
                st = con.createStatement();
                rs = st.executeQuery(q2);
              
                while(rs.next()) 
                { 
                    ac_pass = (rs.getString("aadhar_copy"));
                    bc_pass = (rs.getString("birth_cert_copy"));
                    ic_pass = (rs.getString("income_cert_copy")); 
                    rc_pass = (rs.getString("ration_copy"));
                    mc_pass = (rs.getString("marriage_copy"));
                    dc_pass = (rs.getString("death_copy"));  
                    System.out.println(ac_pass+"\n"+bc_pass+"\n"+ic_pass+"\n"+rc_pass+"\n"+mc_pass+"\n"+dc_pass+"\n");
    
                    if(ac_pass.equalsIgnoreCase("YES"))
                    {
                       acy.setSelected(true);
                    }
                    else
                    {
                       acn.setSelected(true);
                    }
                    if(bc_pass.equalsIgnoreCase("YES"))
                    {
                        bcy.setSelected(true);
                    }
                    else
                    {
                       bcn.setSelected(true);
                    }
                    if(ic_pass.equalsIgnoreCase("YES"))
                    {
                        icy.setSelected(true);
                    }
                    else
                    {
                       icn.setSelected(true);
                    }
                    if(rc_pass.equalsIgnoreCase("YES"))
                    {
                        rcy.setSelected(true);
                    }
                    else
                    {
                       rcn.setSelected(true);
                    }
                    if(mc_pass .equalsIgnoreCase("YES"))
                    {
                        mcn.setSelected(true);
                    }
                    else if(mc_pass.equalsIgnoreCase("NO"))
                    {
                       mcn.setSelected(true);
                    }
                    else
                    {
                        mcn.setEnabled(false);
                        mcy.setEnabled(false); 
                    }
                    if(dc_pass.equalsIgnoreCase("YES"))
                    {
                        dcy.setSelected(true);
                    }
                    else if(dc_pass.equalsIgnoreCase("NO"))
                    {
                       dcn.setSelected(true);
                    }
                    else
                    {
                        dcn.setEnabled(false);
                        dcy.setEnabled(false);   
                    }
                }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submit2ActionPerformed

    private void app_no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_app_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_app_no1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(survey_agent_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(survey_agent_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(survey_agent_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(survey_agent_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new survey_agent_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ac;
    private javax.swing.JRadioButton acn;
    private javax.swing.JRadioButton acy;
    private javax.swing.JTextField app_no;
    private javax.swing.JTextField app_no1;
    private javax.swing.JScrollPane app_sp;
    private javax.swing.ButtonGroup bc;
    private javax.swing.JRadioButton bcn;
    private javax.swing.JRadioButton bcy;
    private javax.swing.ButtonGroup dc;
    private javax.swing.JRadioButton dcn;
    private javax.swing.JRadioButton dcy;
    private javax.swing.JTextField gdp;
    private javax.swing.JButton home1;
    private javax.swing.ButtonGroup ic;
    private javax.swing.JRadioButton icn;
    private javax.swing.JRadioButton icy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> landtype;
    private javax.swing.JButton log_out1;
    private javax.swing.ButtonGroup mc;
    private javax.swing.JRadioButton mcn;
    private javax.swing.JRadioButton mcy;
    private javax.swing.JTextField nof;
    private javax.swing.ButtonGroup rc;
    private javax.swing.JRadioButton rcn;
    private javax.swing.JRadioButton rcy;
    private javax.swing.JScrollPane reg_sp;
    private javax.swing.JTextArea remark;
    private javax.swing.JPanel s_agent_home;
    private javax.swing.JPanel s_rep_app;
    private javax.swing.JPanel s_rep_reg;
    private javax.swing.JLabel sag_no;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JButton submit2;
    private javax.swing.JButton sur_app;
    private javax.swing.JButton sur_reg;
    private javax.swing.JComboBox<String> v;
    private javax.swing.JButton view_det1;
    // End of variables declaration//GEN-END:variables
}
